// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ActivityBannerExcelConfigData = Vec<ActivityBannerExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityBannerExcelConfigDatum {
    #[serde(rename = "activityId")]
    pub activity_id: i64,

    #[serde(rename = "INPFCDCCLON")]
    pub inpfcdcclon: Option<String>,

    #[serde(rename = "rewardPreviewId")]
    pub reward_preview_id: Option<i64>,

    #[serde(rename = "CKPJFAFKDFK")]
    pub ckpjfafkdfk: String,

    #[serde(rename = "prefabPath")]
    pub prefab_path: String,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,

    #[serde(rename = "HHOJIAAHDMK")]
    pub hhojiaahdmk: Option<bool>,
}

pub fn load() -> Result<ActivityBannerExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ActivityBannerExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
