// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ActivityVintageHuntingExcelConfigData = Vec<ActivityVintageHuntingExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityVintageHuntingExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "CNGBDMFLGGF")]
    pub cngbdmflggf: i64,

    #[serde(rename = "openDay")]
    pub open_day: i64,

    #[serde(rename = "IDDONJAJHNM")]
    pub iddonjajhnm: i64,

    #[serde(rename = "guideQuestId")]
    pub guide_quest_id: i64,

    #[serde(rename = "galleryId")]
    pub gallery_id: i64,

    #[serde(rename = "groupId")]
    pub group_id: i64,

    #[serde(rename = "MPEIIPLLCNO")]
    pub mpeiipllcno: i64,

    #[serde(rename = "ACHCCLDFJED")]
    pub achccldfjed: Vec<i64>,

    #[serde(rename = "BAKHECCKLDF")]
    pub bakhecckldf: Vec<i64>,

    #[serde(rename = "AOEBEJKFEBA")]
    pub aoebejkfeba: Vec<i64>,

    #[serde(rename = "tutorialId")]
    pub tutorial_id: i64,

    #[serde(rename = "DFCHALDIOFN")]
    pub dfchaldiofn: i64,

    #[serde(rename = "NGCPNLOBHDP")]
    pub ngcpnlobhdp: i64,

    #[serde(rename = "PBMHBFKDPDP")]
    pub pbmhbfkdpdp: Vec<i64>,

    #[serde(rename = "FKNBALOFCKE")]
    pub fknbalofcke: i64,

    #[serde(rename = "HHKCLJNGIEL")]
    pub hhkcljngiel: i64,
}

pub fn load() -> Result<ActivityVintageHuntingExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ActivityVintageHuntingExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
