// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type BlessingScanPicExcelConfigData = Vec<BlessingScanPicExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct BlessingScanPicExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "grantRewardCost")]
    pub grant_reward_cost: i64,

    #[serde(rename = "iconName")]
    pub icon_name: String,

    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,
}

pub fn load() -> Result<BlessingScanPicExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "BlessingScanPicExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
