// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type BonusTreasureSolutionExcelConfigData = Vec<BonusTreasureSolutionExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct BonusTreasureSolutionExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "LGENGDLHNHK")]
    pub lgengdlhnhk: i64,

    #[serde(rename = "MFFEJAAEHBF")]
    pub mffejaaehbf: i64,

    #[serde(rename = "NABAAPJNECF")]
    pub nabaapjnecf: Vec<i64>,
}

pub fn load() -> Result<BonusTreasureSolutionExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "BonusTreasureSolutionExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
