// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type BuffIconExcelConfigData = Vec<BuffIconExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct BuffIconExcelConfigDatum {
    #[serde(rename = "buffID")]
    pub buff_id: i64,

    #[serde(rename = "icon")]
    pub icon: String,

    #[serde(rename = "mutexType")]
    pub mutex_type: i64,
}

pub fn load() -> Result<BuffIconExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "BuffIconExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
