// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ChannellerSlabLoopDungeonExcelConfigData = Vec<ChannellerSlabLoopDungeonExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChannellerSlabLoopDungeonExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "openDay")]
    pub open_day: i64,

    #[serde(rename = "titleTextMapHash")]
    pub title_text_map_hash: i64,

    #[serde(rename = "contentTextMapHash")]
    pub content_text_map_hash: i64,

    #[serde(rename = "monsterIdVec")]
    pub monster_id_vec: Vec<i64>,

    #[serde(rename = "limitingConditionVec")]
    pub limiting_condition_vec: Vec<i64>,

    #[serde(rename = "firstPassRewardId")]
    pub first_pass_reward_id: i64,
}

pub fn load() -> Result<ChannellerSlabLoopDungeonExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ChannellerSlabLoopDungeonExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
