// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type CustomGadgetTabExcelConfigData = Vec<CustomGadgetTabExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct CustomGadgetTabExcelConfigDatum {
    #[serde(rename = "ODBDHLCFIOI")]
    pub odbdhlcfioi: i64,

    #[serde(rename = "tabNameTextMapHash")]
    pub tab_name_text_map_hash: i64,

    #[serde(rename = "BAPJKDMIIKC")]
    pub bapjkdmiikc: Vec<String>,

    #[serde(rename = "MALHNNBHNGL")]
    pub malhnnbhngl: Malhnnbhngl,

    #[serde(rename = "JIMKJHNFFEN")]
    pub jimkjhnffen: Jimkjhnffen,

    #[serde(rename = "HADPJDHCNGK")]
    pub hadpjdhcngk: i64,

    #[serde(rename = "CDPHHBAENJC")]
    pub cdphhbaenjc: i64,

    #[serde(rename = "PJKGENLMCNB")]
    pub pjkgenlmcnb: Option<i64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Jimkjhnffen {
    #[serde(rename = "Eff_SceneObj_FlowerShlef_Switch")]
    EffSceneObjFlowerShlefSwitch,

    #[serde(rename = "Eff_SceneObj_Flower_Switch")]
    EffSceneObjFlowerSwitch,

    #[serde(rename = "")]
    Empty,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Malhnnbhngl {
    #[serde(rename = "Eff_SceneObj_FlowerPot_Selected")]
    EffSceneObjFlowerPotSelected,

    #[serde(rename = "Eff_SceneObj_FlowerShlef_Switch")]
    EffSceneObjFlowerShlefSwitch,

    #[serde(rename = "Eff_SceneObj_Irodori_Flower_Selected")]
    EffSceneObjIrodoriFlowerSelected,

    #[serde(rename = "")]
    Empty,
}

pub fn load() -> Result<CustomGadgetTabExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "CustomGadgetTabExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
