// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type LampProgressControlConfigData = Vec<LampProgressControlConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LampProgressControlConfigDatum {
    #[serde(rename = "hour")]
    pub hour: i64,

    #[serde(rename = "minProgress")]
    pub min_progress: i64,

    #[serde(rename = "maxProgress")]
    pub max_progress: i64,
}

pub fn load() -> Result<LampProgressControlConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "LampProgressControlConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
