// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type LampRegionDataConfigData = Vec<LampRegionDataConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LampRegionDataConfigDatum {
    #[serde(rename = "region")]
    pub region: String,

    #[serde(rename = "factor")]
    pub factor: i64,
}

pub fn load() -> Result<LampRegionDataConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "LampRegionDataConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
