// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type LimitRegionExcelConfigData = Vec<LimitRegionExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LimitRegionExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "name")]
    pub name: String,

    #[serde(rename = "sceneId")]
    pub scene_id: i64,

    #[serde(rename = "type")]
    pub limit_region_excel_config_datum_type: Type,

    #[serde(rename = "ADCPJOMDBBN")]
    pub adcpjomdbbn: Option<String>,

    #[serde(rename = "order")]
    pub order: Option<i64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "LIMIT_REGION_TYPE_ACTIVITY")]
    LimitRegionTypeActivity,

    #[serde(rename = "LIMIT_REGION_TYPE_BIGWORLD")]
    LimitRegionTypeBigworld,

    #[serde(rename = "LIMIT_REGION_TYPE_HOMEWORLD")]
    LimitRegionTypeHomeworld,
}

pub fn load() -> Result<LimitRegionExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "LimitRegionExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
