// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type LockTemplateExcelConfigData = Vec<LockTemplateExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LockTemplateExcelConfigDatum {
    #[serde(rename = "type")]
    pub lock_template_excel_config_datum_type: String,

    #[serde(rename = "range")]
    pub range: f64,

    #[serde(rename = "normalPri")]
    pub normal_pri: Option<f64>,

    #[serde(rename = "combatPri")]
    pub combat_pri: Option<f64>,
}

pub fn load() -> Result<LockTemplateExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "LockTemplateExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
