// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type MechanicusCardCurseExcelConfigData = Vec<MechanicusCardCurseExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct MechanicusCardCurseExcelConfigDatum {
    #[serde(rename = "ID")]
    pub id: i64,

    #[serde(rename = "effectID")]
    pub effect_id: i64,

    #[serde(rename = "lastRound")]
    pub last_round: Option<i64>,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,

    #[serde(rename = "descParamList")]
    pub desc_param_list: Vec<String>,
}

pub fn load() -> Result<MechanicusCardCurseExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "MechanicusCardCurseExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
