// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type MichiaeWatcherExcelConfigData = Vec<MichiaeWatcherExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct MichiaeWatcherExcelConfigDatum {
    #[serde(rename = "watcherId")]
    pub watcher_id: i64,

    #[serde(rename = "NBLOCEJHFCN")]
    pub nblocejhfcn: i64,

    #[serde(rename = "HPIKALMBHLL")]
    pub hpikalmbhll: i64,
}

pub fn load() -> Result<MichiaeWatcherExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "MichiaeWatcherExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
