// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type WorldExcelConfigData = Vec<WorldExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct WorldExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "type")]
    pub world_excel_config_datum_type: String,

    #[serde(rename = "mainSceneId")]
    pub main_scene_id: i64,

    #[serde(rename = "subSceneIdVec")]
    pub sub_scene_id_vec: Vec<i64>,
}

pub fn load() -> Result<WorldExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "WorldExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
