/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type AbilityOverrideExcelConfigData = Vec<AbilityOverrideExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct AbilityOverrideExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "abilityName")]
    pub ability_name: String,
    pub jokfboipmmi: Vec<Jokfboipmmi>,
    pub jfmjccnedkp: Vec<String>,
    pub gioifflhdge: Vec<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct Jokfboipmmi {
    pub njlofdbapkh: String,
    pub gelhpbemnme: Option<f64>,
}
