/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type AbilityPropExcelConfigData = Vec<AbilityPropExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AbilityPropExcelConfigDatum {
    pub prop_name: String,
    pub overall_min: Option<f64>,
    pub overall_max: Option<f64>,
    pub limit_tag_min: Option<f64>,
    pub limit_tag_max: Option<f64>,
}
