/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivitySpiceFoodExcelConfigData = Vec<ActivitySpiceFoodExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivitySpiceFoodExcelConfigDatum {
    pub source_desc_text_map_hash: i64,
    pub special_food_id: i64,
    pub normal_food_id: i64,
    pub recipe_mat_id: i64,
}
