/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityPotionModeChoiceExcelConfigData = Vec<ActivityPotionModeChoiceExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivityPotionModeChoiceExcelConfigDatum {
    pub mode_id: i64,
    pub desc_text_map_hash: i64,
    pub score_ratio: f64,
    pub dungeon_level: i64,
}
