// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityGearGadgetShaftExcelConfigData = Vec<ActivityGearGadgetShaftExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityGearGadgetShaftExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "gadgetID")]
    pub gadget_id: i64,

    #[serde(rename = "radius")]
    pub radius: f64,

    #[serde(rename = "ODBKHFNPEFL")]
    pub odbkhfnpefl: Vec<f64>,

    #[serde(rename = "OCFFGOMFFNC")]
    pub ocffgomffnc: f64,

    #[serde(rename = "HCONDFDNJIK")]
    pub hcondfdnjik: Vec<f64>,
}

pub fn load() -> Result<ActivityGearGadgetShaftExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ActivityGearGadgetShaftExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
