// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityPhotographPosExcelConfigData = Vec<ActivityPhotographPosExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityPhotographPosExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "JKAMKKGPBBJ")]
    pub jkamkkgpbbj: i64,

    #[serde(rename = "DLMDAIIKNDD")]
    pub dlmdaiikndd: i64,

    #[serde(rename = "MKGHEFMNFLM")]
    pub mkghefmnflm: i64,

    #[serde(rename = "PKKMJHPJNAO")]
    pub pkkmjhpjnao: i64,

    #[serde(rename = "CFCLCPCKBII")]
    pub cfclcpckbii: i64,

    #[serde(rename = "IOCKFBMDAEO")]
    pub iockfbmdaeo: i64,

    #[serde(rename = "PFOBEJHPNJE")]
    pub pfobejhpnje: String,

    #[serde(rename = "GNLEOEOCGEM")]
    pub gnleoeocgem: String,

    #[serde(rename = "DBALNKCPMIJ")]
    pub dbalnkcpmij: i64,

    #[serde(rename = "LEJDOAADLCB")]
    pub lejdoaadlcb: i64,

    #[serde(rename = "IIKINAJDBJF")]
    pub iikinajdbjf: Vec<i64>,

    #[serde(rename = "MFGHBGKMAJI")]
    pub mfghbgkmaji: Vec<i64>,

    #[serde(rename = "openDay")]
    pub open_day: i64,

    #[serde(rename = "watcherId")]
    pub watcher_id: i64,

    #[serde(rename = "galleryId")]
    pub gallery_id: i64,

    #[serde(rename = "AGJPLMJGBIN")]
    pub agjplmjgbin: i64,

    #[serde(rename = "COOGIDFOEAO")]
    pub coogidfoeao: i64,

    #[serde(rename = "OGJEGLGFFJJ")]
    pub ogjeglgffjj: i64,

    #[serde(rename = "HNBBHIHLICO")]
    pub hnbbhihlico: i64,

    #[serde(rename = "EDJAOFLGIBC")]
    pub edjaoflgibc: Vec<String>,

    #[serde(rename = "BOHJJLANIBG")]
    pub bohjjlanibg: Vec<String>,

    #[serde(rename = "sceneID")]
    pub scene_id: i64,
}

pub fn load() -> Result<ActivityPhotographPosExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ActivityPhotographPosExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
