/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityVintagePresentExcelConfigData = Vec<ActivityVintagePresentExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct ActivityVintagePresentExcelConfigDatum {
    pub bnpfomkeapl: i64,
    pub ihhcmmklokm: i64,
    #[serde(rename = "openDay")]
    pub open_day: i64,
    #[serde(rename = "groupIdList")]
    pub group_id_list: Vec<i64>,
    pub okbeaflcaii: Vec<i64>,
    pub ebgfaempejb: i64,
    #[serde(rename = "rewardId")]
    pub reward_id: i64,
    pub dmbfkmalogf: Dmbfkmalogf,
    pub fppgpneicdn: String,
    pub ljnieigkeci: i64,
    pub kfekoangacc: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Dmbfkmalogf {
    #[serde(rename = "PRESENT_TYPE_NORMAL")]
    PresentTypeNormal,
    #[serde(rename = "PRESENT_TYPE_SPECIAL")]
    PresentTypeSpecial,
}
