/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityGachaRobotExcelConfigData = Vec<ActivityGachaRobotExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct ActivityGachaRobotExcelConfigDatum {
    pub aafifjbcegl: i64,
    pub pnicingggca: Vec<i64>,
    pub mlaoicfkgce: Vec<i64>,
    #[serde(rename = "consumeItemId")]
    pub consume_item_id: Vec<i64>,
    #[serde(rename = "type")]
    pub activity_gacha_robot_excel_config_datum_type: Type,
    pub hbdjjofogjb: i64,
    #[serde(rename = "materialId")]
    pub material_id: i64,
    #[serde(rename = "modelPath")]
    pub model_path: String,
    pub jmpbiojajjk: i64,
    pub flfnnlhnffp: i64,
    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,
    pub kpejejieiag: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Type {
    #[serde(rename = "ROBOT_TYPE_HIDDEN")]
    RobotTypeHidden,
    #[serde(rename = "ROBOT_TYPE_NORMAL")]
    RobotTypeNormal,
}
