// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ActivityVintageQuestDataExcelConfigData = Vec<ActivityVintageQuestDataExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityVintageQuestDataExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "questId")]
    pub quest_id: i64,

    #[serde(rename = "JKMIPDOFBCD")]
    pub jkmipdofbcd: i64,

    #[serde(rename = "chapterTitleTextMapHash")]
    pub chapter_title_text_map_hash: i64,

    #[serde(rename = "DGGMIFJMJBP")]
    pub dggmifjmjbp: i64,

    #[serde(rename = "HMMIBLBGDAN")]
    pub hmmiblbgdan: i64,

    #[serde(rename = "preQuestId")]
    pub pre_quest_id: Option<i64>,
}

pub fn load() -> Result<ActivityVintageQuestDataExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ActivityVintageQuestDataExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
