// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityVintageMarketPrepareExcelConfigData = Vec<ActivityVintageMarketPrepareExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityVintageMarketPrepareExcelConfigDatum {
    #[serde(rename = "configID")]
    pub config_id: i64,

    #[serde(rename = "LOJMLNMBCGO")]
    pub lojmlnmbcgo: i64,

    #[serde(rename = "DKFEBIGCMLM")]
    pub dkfebigcmlm: Option<String>,

    #[serde(rename = "MPJOGABPIPC")]
    pub mpjogabpipc: String,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,

    #[serde(rename = "OOCPOAHBPKB")]
    pub oocpoahbpkb: i64,

    #[serde(rename = "JFPDPIJKCAA")]
    pub jfpdpijkcaa: i64,

    #[serde(rename = "BHMNMCODBCL")]
    pub bhmnmcodbcl: Option<i64>,

    #[serde(rename = "CCNALILEPJF")]
    pub ccnalilepjf: Option<i64>,

    #[serde(rename = "BBHGBIIHBBC")]
    pub bbhgbiihbbc: i64,

    #[serde(rename = "AKIHONDGKJN")]
    pub akihondgkjn: i64,
}

pub fn load() -> Result<ActivityVintageMarketPrepareExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ActivityVintageMarketPrepareExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
