// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityMapTypeExcelConfigData = Vec<ActivityMapTypeExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityMapTypeExcelConfigDatum {
    #[serde(rename = "type")]
    pub activity_map_type_excel_config_datum_type: String,

    #[serde(rename = "FMPJAAOEFNK")]
    pub fmpjaaoefnk: String,
}

pub fn load() -> Result<ActivityMapTypeExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ActivityMapTypeExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
