/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivitySpiceFoodExcelConfigData = Vec<ActivitySpiceFoodExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct ActivitySpiceFoodExcelConfigDatum {
    pub lfiflmpaipo: i64,
    pub ocfcpdlpfin: i64,
    pub meedendeidd: i64,
    pub knbneagkido: i64,
}
