// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type ActivityChessPreviewExcelConfigData = Vec<ActivityChessPreviewExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityChessPreviewExcelConfigDatum {
    #[serde(rename = "activityID")]
    pub activity_id: i64,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,

    #[serde(rename = "rewardPreviewID")]
    pub reward_preview_id: i64,

    #[serde(rename = "KPEKFDBANJE")]
    pub kpekfdbanje: i64,

    #[serde(rename = "LGIJFGOJIEK")]
    pub lgijfgojiek: i64,

    #[serde(rename = "watcherList")]
    pub watcher_list: Vec<i64>,

    #[serde(rename = "matchPlayerLimit")]
    pub match_player_limit: i64,

    #[serde(rename = "BAJJDHLOIJA")]
    pub bajjdhloija: bool,

    #[serde(rename = "IPAGCNONFLF")]
    pub ipagcnonflf: i64,

    #[serde(rename = "IOKMMOOFBAK")]
    pub iokmmoofbak: i64,

    #[serde(rename = "punishTime")]
    pub punish_time: i64,

    #[serde(rename = "LFKKMMJANOC")]
    pub lfkkmmjanoc: i64,

    #[serde(rename = "KPGFELNHDPC")]
    pub kpgfelnhdpc: i64,

    #[serde(rename = "CFFAOKDNALC")]
    pub cffaokdnalc: Vec<i64>,
}

pub fn load() -> Result<ActivityChessPreviewExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ActivityChessPreviewExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
