// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type ActivityPhotographPosExcelConfigData = Vec<ActivityPhotographPosExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityPhotographPosExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "IJMPOKMLHNF")]
    pub ijmpokmlhnf: i64,

    #[serde(rename = "IHOBPPIOEIL")]
    pub ihobppioeil: i64,

    #[serde(rename = "CCFOPDEIIIE")]
    pub ccfopdeiiie: i64,

    #[serde(rename = "FIFOOFJOOIP")]
    pub fifoofjooip: i64,

    #[serde(rename = "LGFBKBPLMCN")]
    pub lgfbkbplmcn: i64,

    #[serde(rename = "PLHCEEHBBFM")]
    pub plhceehbbfm: i64,

    #[serde(rename = "JLCGNMKEHPP")]
    pub jlcgnmkehpp: String,

    #[serde(rename = "CAKIPMCPOEA")]
    pub cakipmcpoea: String,

    #[serde(rename = "OOGIMLJKEDC")]
    pub oogimljkedc: i64,

    #[serde(rename = "AGLMPHJDFMF")]
    pub aglmphjdfmf: i64,

    #[serde(rename = "FJMEOOJGKLG")]
    pub fjmeoojgklg: Vec<i64>,

    #[serde(rename = "NNKJCCIJBAL")]
    pub nnkjccijbal: Vec<i64>,

    #[serde(rename = "openDay")]
    pub open_day: i64,

    #[serde(rename = "watcherId")]
    pub watcher_id: i64,

    #[serde(rename = "galleryId")]
    pub gallery_id: i64,

    #[serde(rename = "HLOODCPKDCK")]
    pub hloodcpkdck: i64,

    #[serde(rename = "OHMELCKGJKE")]
    pub ohmelckgjke: i64,

    #[serde(rename = "HEPCHBCANAG")]
    pub hepchbcanag: i64,

    #[serde(rename = "PPIPHJPCFIH")]
    pub ppiphjpcfih: i64,

    #[serde(rename = "LAEDLIOFLOF")]
    pub laedlioflof: Vec<String>,

    #[serde(rename = "FKINPIGODJE")]
    pub fkinpigodje: Vec<String>,

    #[serde(rename = "sceneID")]
    pub scene_id: i64,
}

pub fn load() -> Result<ActivityPhotographPosExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ActivityPhotographPosExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
