/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityUpAvatarExcelConfigData = Vec<ActivityUpAvatarExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivityUpAvatarExcelConfigDatum {
    pub id: i64,
    pub activity_id: i64,
    pub name_text_map_hash: i64,
    pub avatar_id_list: Vec<i64>,
}
