// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ActivityRockBoardExploreQuestExcelConfigData = Vec<ActivityRockBoardExploreQuestExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityRockBoardExploreQuestExcelConfigDatum {
    #[serde(rename = "MGNHACIGAJJ")]
    pub mgnhacigajj: i64,

    #[serde(rename = "questID")]
    pub quest_id: i64,

    #[serde(rename = "openDay")]
    pub open_day: i64,

    #[serde(rename = "iconName")]
    pub icon_name: String,

    #[serde(rename = "DGGMIFJMJBP")]
    pub dggmifjmjbp: i64,

    #[serde(rename = "HMMIBLBGDAN")]
    pub hmmiblbgdan: i64,
}

pub fn load() -> Result<ActivityRockBoardExploreQuestExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ActivityRockBoardExploreQuestExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
