// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityVintageHuntingExcelConfigData = Vec<ActivityVintageHuntingExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityVintageHuntingExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "CMBPCEKICHA")]
    pub cmbpcekicha: i64,

    #[serde(rename = "openDay")]
    pub open_day: i64,

    #[serde(rename = "NGIDMFJMANC")]
    pub ngidmfjmanc: i64,

    #[serde(rename = "guideQuestId")]
    pub guide_quest_id: i64,

    #[serde(rename = "galleryId")]
    pub gallery_id: i64,

    #[serde(rename = "groupId")]
    pub group_id: i64,

    #[serde(rename = "IAMPPODHFNN")]
    pub iamppodhfnn: i64,

    #[serde(rename = "IPDEINDKDBC")]
    pub ipdeindkdbc: Vec<i64>,

    #[serde(rename = "NKAMKDOPODO")]
    pub nkamkdopodo: Vec<i64>,

    #[serde(rename = "KAHAIAHOPMH")]
    pub kahaiahopmh: Vec<i64>,

    #[serde(rename = "tutorialId")]
    pub tutorial_id: i64,

    #[serde(rename = "IFKKGKLCMFO")]
    pub ifkkgklcmfo: i64,

    #[serde(rename = "CFKMNGOENAP")]
    pub cfkmngoenap: i64,

    #[serde(rename = "GDBGGBADKML")]
    pub gdbggbadkml: Vec<i64>,

    #[serde(rename = "DLOMFAJOCKM")]
    pub dlomfajockm: i64,

    #[serde(rename = "JIMDIMFMCAM")]
    pub jimdimfmcam: i64,
}

pub fn load() -> Result<ActivityVintageHuntingExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ActivityVintageHuntingExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
