// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ActivityGearGadgetGearExcelConfigData = Vec<ActivityGearGadgetGearExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityGearGadgetGearExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "gadgetID")]
    pub gadget_id: i64,

    #[serde(rename = "EGINMJAFHCP")]
    pub eginmjafhcp: Vec<f64>,

    #[serde(rename = "IJJJLHGLNKE")]
    pub ijjjlhglnke: Vec<i64>,

    #[serde(rename = "materialID")]
    pub material_id: i64,

    #[serde(rename = "BPGCLMJOLGL")]
    pub bpgclmjolgl: String,

    #[serde(rename = "ANCLLCMHEGA")]
    pub ancllcmhega: String,

    #[serde(rename = "IPKALPKLINE")]
    pub ipkalpkline: String,
}

pub fn load() -> Result<ActivityGearGadgetGearExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ActivityGearGadgetGearExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
