// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityRockBoardExploreQuestExcelConfigData = Vec<ActivityRockBoardExploreQuestExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityRockBoardExploreQuestExcelConfigDatum {
    #[serde(rename = "DMFHECPKOJN")]
    pub dmfhecpkojn: i64,

    #[serde(rename = "questID")]
    pub quest_id: i64,

    #[serde(rename = "openDay")]
    pub open_day: i64,

    #[serde(rename = "iconName")]
    pub icon_name: String,

    #[serde(rename = "EHDEMGOKAML")]
    pub ehdemgokaml: i64,

    #[serde(rename = "JDFEPFFJNCO")]
    pub jdfepffjnco: i64,
}

pub fn load() -> Result<ActivityRockBoardExploreQuestExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ActivityRockBoardExploreQuestExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
