/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityPlantFlowerMainExcelConfigData = Vec<ActivityPlantFlowerMainExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct ActivityPlantFlowerMainExcelConfigDatum {
    #[serde(rename = "scheduleId")]
    pub schedule_id: i64,
    pub abeakpkjdkp: Vec<i64>,
    pub hiejaoooiae: Vec<i64>,
    pub lecfibbokaj: i64,
    #[serde(rename = "rewardPreviewId")]
    pub reward_preview_id: i64,
    pub jjhobplbhgn: i64,
    pub efohheobhfi: Vec<i64>,
    #[serde(rename = "openQuestId")]
    pub open_quest_id: i64,
    pub bgboncgdbgf: i64,
    #[serde(rename = "dailyConfigIdList")]
    pub daily_config_id_list: Vec<i64>,
}
