// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ActivityChessAffixExcelConfigData = Vec<ActivityChessAffixExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ActivityChessAffixExcelConfigDatum {
    #[serde(rename = "ID")]
    pub id: i64,

    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,
}

pub fn load() -> Result<ActivityChessAffixExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ActivityChessAffixExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
