/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityGcgpveInfiniteMonsterScoreExcelConfigData = Vec<ActivityGcgpveInfiniteMonsterScoreExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActivityGcgpveInfiniteMonsterScoreExcelConfigDatum {
    pub id: i64,
    #[serde(rename = "DIKKDJCENFG")]
    pub dikkdjcenfg: i64,
    pub score: i64,
    #[serde(rename = "LBLDBBJMMMK")]
    pub lbldbbjmmmk: i64,
}
