/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivitySpiceExcelConfigData = Vec<ActivitySpiceExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivitySpiceExcelConfigDatum {
    pub id: i64,
    pub activity_id: i64,
    pub schedule_id: i64,
    pub spice_id: i64,
    pub watcher_id_list: Vec<i64>,
    pub fetter_value: i64,
    pub extra_width: i64,
    #[serde(rename = "preQuestID")]
    pub pre_quest_id: i64,
}
