/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityVintageMarketPrepareExcelConfigData = Vec<ActivityVintageMarketPrepareExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct ActivityVintageMarketPrepareExcelConfigDatum {
    #[serde(rename = "configID")]
    pub config_id: i64,
    pub jgglonlbhbo: i64,
    pub maoidcmanbh: Option<String>,
    pub eikhpncgboe: String,
    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,
    pub jndceaeljdg: i64,
    pub famneefmonm: i64,
    pub dmmlmehlljk: Option<i64>,
    pub neddhljbdol: Option<i64>,
    pub kknefohdgfi: i64,
    pub fgpgighpjch: i64,
}
