/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityCrystalLinkCondBuffExcelConfigData = Vec<ActivityCrystalLinkCondBuffExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct ActivityCrystalLinkCondBuffExcelConfigDatum {
    #[serde(rename = "buffId")]
    pub buff_id: i64,
    pub beijhjhdkjd: String,
    #[serde(rename = "abilityName")]
    pub ability_name: String,
    pub habfbjodndm: i64,
    pub ekgheojhnci: i64,
    pub ajbflbfipdg: f64,
    pub mapehmdkibd: Vec<String>,
}
