/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ActivityVintagePlayTypeExcelConfigData = Vec<ActivityVintagePlayTypeExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ActivityVintagePlayTypeExcelConfigDatum {
    pub id: i64,
    pub open_day: i64,
    #[serde(rename = "ACIMFILFKLK")]
    pub acimfilfklk: i64,
    #[serde(rename = "MBMGLHGMPOL")]
    pub mbmglhgmpol: i64,
    #[serde(rename = "APFOLDJFMCG")]
    pub apfoldjfmcg: Option<i64>,
    pub guide_quest_id: Option<i64>,
    pub tutorial_id: Option<i64>,
}
