/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type AdjustFirebaseGachaExcelConfigData = Vec<AdjustFirebaseGachaExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct AdjustFirebaseGachaExcelConfigDatum {
    pub id: i64,
    pub bilkkiiinkp: i64,
    pub pmglpilpmpe: String,
}
