/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type AkaFesArchitectComponentExcelConfigData = Vec<AkaFesArchitectComponentExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct AkaFesArchitectComponentExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    pub moomaancllo: i64,
    pub lcmkdpecape: i64,
    pub nlnopnkpghm: String,
}
