/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type AkaFesRhythmExcelConfigData = Vec<AkaFesRhythmExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AkaFesRhythmExcelConfigDatum {
    pub id: i64,
    pub open_day: i64,
    pub level_name_text_map_hash: i64,
    pub score: i64,
    #[serde(rename = "KAIKDECFGGD")]
    pub kaikdecfggd: String,
    pub dungeon_id: i64,
    pub gallery_id: i64,
    #[serde(rename = "CDBGPGGBHGM")]
    pub cdbgpggbhgm: i64,
    #[serde(rename = "IJEPCACFMOF")]
    pub ijepcacfmof: i64,
    pub watcher_id: Vec<i64>,
    pub tutorial_id: i64,
    #[serde(rename = "DKDMCJLKOAC")]
    pub dkdmcjlkoac: i64,
    #[serde(rename = "PLHIGBEDGBD")]
    pub plhigbedgbd: i64,
    #[serde(rename = "KIEDPELJONH")]
    pub kiedpeljonh: Vec<i64>,
    #[serde(rename = "type")]
    pub aka_fes_rhythm_excel_config_datum_type: Option<String>,
}
