/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type AkaFesReasoningQuestionExcelConfigData = Vec<AkaFesReasoningQuestionExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct AkaFesReasoningQuestionExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    pub bbeigemamlb: i64,
    pub obgjollkold: Option<Obgjollkold>,
    pub nfcmkfhkkal: Vec<i64>,
    #[serde(rename = "sortId")]
    pub sort_id: i64,
    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,
    pub nnnfdbnnpko: i64,
    pub dpmkaeijebf: i64,
    pub khabigohabl: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Obgjollkold {
    #[serde(rename = "NO")]
    No,
    #[serde(rename = "YES")]
    Yes,
}
