/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type AudioBattleFervorChestStgConfigData = Vec<AudioBattleFervorChestStgConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct AudioBattleFervorChestStgConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    pub agcmpdabmia: f64,
    pub gdpaonnebco: i64,
    pub mcibgcfbmbl: f64,
    pub anmomgiapai: i64,
}
