/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type AudioBattleFervorCollectionStageConfigData = Vec<AudioBattleFervorCollectionStageConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct AudioBattleFervorCollectionStageConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    pub clgnknpgpig: f64,
    pub nhiflakhdkm: i64,
    pub hckjamaeogm: f64,
    pub bjnojadebhg: Vec<Bjnojadebhg>,
    pub odggnojlbal: Vec<Odggnojlbal>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct Bjnojadebhg {
    pub jeclgoopbna: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct Odggnojlbal {
    pub oeehnogdbib: i64,
}
