// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type AvatarExtraPropExcelConfigData = Vec<AvatarExtraPropExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct AvatarExtraPropExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "EMIHGBDPBGN")]
    pub emihgbdpbgn: Vec<Emihgbdpbgn>,

    #[serde(rename = "JJNNIGJAJEG")]
    pub jjnnigjajeg: i64,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Emihgbdpbgn {
    #[serde(rename = "propType")]
    pub prop_type: Option<String>,

    #[serde(rename = "propValue")]
    pub prop_value: Option<i64>,
}

pub fn load() -> Result<AvatarExtraPropExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "AvatarExtraPropExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
