/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type BartenderEventExcelConfigData = Vec<BartenderEventExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct BartenderEventExcelConfigDatum {
    #[serde(rename = "effectName")]
    pub effect_name: String,
    pub cjckhiibanb: Option<Cjckhiibanb>,
    pub bgdjgcpaoan: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Cjckhiibanb {
    #[serde(rename = "BARTENDER_FINISH_CUP_EFF")]
    BartenderFinishCupEff,
    #[serde(rename = "BARTENDER_FINISH_CUP_ONHAND")]
    BartenderFinishCupOnhand,
    #[serde(rename = "BARTENDER_FINISH_CUP_ONTABLE")]
    BartenderFinishCupOntable,
    #[serde(rename = "BARTENDER_FINISH_CUP_OVER")]
    BartenderFinishCupOver,
    #[serde(rename = "BARTENDER_FINISH_CUP_PUSH")]
    BartenderFinishCupPush,
    #[serde(rename = "BARTENDER_FINISH_POUR_EFF")]
    BartenderFinishPourEff,
    #[serde(rename = "BARTENDER_INGREDIENTS")]
    BartenderIngredients,
    #[serde(rename = "BARTENDER_INGREDIENTS_POUR_EFF")]
    BartenderIngredientsPourEff,
    #[serde(rename = "BARTENDER_MIX_BAR")]
    BartenderMixBar,
    #[serde(rename = "BARTENDER_ORIGIN_CUP_ONHAND")]
    BartenderOriginCupOnhand,
}
