/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type BlitzRushStageExcelConfigData = Vec<BlitzRushStageExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BlitzRushStageExcelConfigDatum {
    pub id: i64,
    pub open_day: i64,
    pub watcher_id_list: Vec<i64>,
    pub stage_title_text_map_hash: i64,
    pub game_play_desc_text_map_hash: i64,
    pub guidetask_desc_text_map_hash: i64,
    #[serde(rename = "guideQuestID")]
    pub guide_quest_id: i64,
    pub push_tips_id: i64,
}
