/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type BlossomChestExcelConfigData = Vec<BlossomChestExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BlossomChestExcelConfigDatum {
    pub id: i64,
    pub chest_gadget_id: i64,
    pub world_resin: Option<i64>,
    pub resin: Option<i64>,
    pub refresh_type: String,
    pub client_show_type: Option<String>,
}
