/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type BoredCreateMonsterExcelConfigData = Vec<BoredCreateMonsterExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BoredCreateMonsterExcelConfigDatum {
    pub player_level: i64,
    pub monster_config_vec: Vec<MonsterConfigVec>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct MonsterConfigVec {
    pub weight: Option<i64>,
    pub id: Option<i64>,
}
