/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type BrickBreakerStageExcelConfigData = Vec<BrickBreakerStageExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct BrickBreakerStageExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    pub mfmnjaeekij: Vec<i64>,
    pub bpabepgibmb: i64,
    #[serde(rename = "openDay")]
    pub open_day: i64,
    pub mnggpmanona: Vec<Vec<i64>>,
    pub dffhhnpibpk: Vec<i64>,
}
