/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type BuffExcelConfigData = Vec<BuffExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct BuffExcelConfigDatum {
    pub group_id: Option<i64>,
    pub name: String,
    pub desc: String,
    pub time: Option<f64>,
    pub is_persistent: Option<bool>,
    pub server_buff_id: i64,
    pub server_buff_type: ServerBuffType,
    pub ability_name: String,
    pub modifier_name: String,
    #[serde(rename = "LDGOIPOCLCA")]
    pub ldgoipoclca: Option<bool>,
    pub stack_type: Option<StackType>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ServerBuffType {
    #[serde(rename = "SERVER_BUFF_AVATAR")]
    ServerBuffAvatar,
    #[serde(rename = "SERVER_BUFF_TEAM")]
    ServerBuffTeam,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum StackType {
    #[serde(rename = "BUFF_STACK")]
    BuffStack,
}
