// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type BuoyantCombatLevelExcelConfigData = Vec<BuoyantCombatLevelExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct BuoyantCombatLevelExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "galleryId")]
    pub gallery_id: i64,

    #[serde(rename = "groupId")]
    pub group_id: i64,

    #[serde(rename = "dayIndex")]
    pub day_index: i64,

    #[serde(rename = "rewardPreview")]
    pub reward_preview: i64,

    #[serde(rename = "GEFICGMHOGK")]
    pub geficgmhogk: i64,

    #[serde(rename = "OKEGJABPGAD")]
    pub okegjabpgad: i64,

    #[serde(rename = "LFHBNHPDLHD")]
    pub lfhbnhpdlhd: Vec<i64>,

    #[serde(rename = "JDOELJDKKDJ")]
    pub jdoeljdkkdj: Vec<i64>,

    #[serde(rename = "recommendLevel")]
    pub recommend_level: Vec<i64>,

    #[serde(rename = "JCDDHAOJGKL")]
    pub jcddhaojgkl: Vec<f64>,
}

pub fn load() -> Result<BuoyantCombatLevelExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "BuoyantCombatLevelExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
