// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ChannellerSlabLoopDungeonRewardExcelConfigData = Vec<ChannellerSlabLoopDungeonRewardExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChannellerSlabLoopDungeonRewardExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "scoreGrade")]
    pub score_grade: i64,

    #[serde(rename = "rewardID")]
    pub reward_id: i64,
}

pub fn load() -> Result<ChannellerSlabLoopDungeonRewardExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ChannellerSlabLoopDungeonRewardExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
