/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ChannellerSlabLevelExcelConfigData = Vec<ChannellerSlabLevelExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannellerSlabLevelExcelConfigDatum {
    pub id: i64,
    #[serde(rename = "stageID")]
    pub stage_id: i64,
    #[serde(rename = "waveID")]
    pub wave_id: i64,
    pub point_name_text_map_hash: i64,
    pub camp_name_text_map_hash: i64,
    pub desc_text_map_hash: i64,
    #[serde(rename = "rewardID")]
    pub reward_id: i64,
    #[serde(rename = "groupID")]
    pub group_id: i64,
}
