/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ChannellerSlabDungeonExcelConfigData = Vec<ChannellerSlabDungeonExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChannellerSlabDungeonExcelConfigDatum {
    #[serde(rename = "stageID")]
    pub stage_id: i64,
    #[serde(rename = "dungeonID")]
    pub dungeon_id: i64,
    #[serde(rename = "rewardID")]
    pub reward_id: i64,
    #[serde(rename = "pointID")]
    pub point_id: i64,
    pub pos: Vec<Option<serde_json::Value>>,
    pub title_text_map_hash: i64,
    pub desc_text_map_hash: i64,
}
