/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ChargeBarStyleExcelConfigData = Vec<ChargeBarStyleExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ChargeBarStyleExcelConfigDatum {
    pub id: i64,
    pub icon_name: String,
    pub fill_effect_type: Option<String>,
}
