// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type ChestLevelSetConfigData = Vec<ChestLevelSetConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ChestLevelSetConfigDatum {
    #[serde(rename = "chestLevel")]
    pub chest_level: i64,

    #[serde(rename = "zoneMinLevel")]
    pub zone_min_level: i64,
}

pub fn load() -> Result<ChestLevelSetConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "ChestLevelSetConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
