// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type CombatEndCleanExcelConfigData = Vec<CombatEndCleanExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct CombatEndCleanExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "OHDKCCOMHBL")]
    pub ohdkccomhbl: String,

    #[serde(rename = "GJOHPMDMMPN")]
    pub gjohpmdmmpn: Vec<Gjohpmdmmpn>,

    #[serde(rename = "JAOBMGJBALN")]
    pub jaobmgjbaln: Vec<Jaobmgjbaln>,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Gjohpmdmmpn {
    #[serde(rename = "Corruption")]
    Corruption,

    #[serde(rename = "None")]
    None,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Jaobmgjbaln {
    #[serde(rename = "")]
    Empty,

    #[serde(rename = "LevelEntity_ClearLocalGadgets")]
    LevelEntityClearLocalGadgets,
}

pub fn load() -> Result<CombatEndCleanExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "CombatEndCleanExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
