// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type CoopInteractionExcelConfigData = Vec<CoopInteractionExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct CoopInteractionExcelConfigDatum {
    #[serde(rename = "idRawNum")]
    pub id_raw_num: i64,

    #[serde(rename = "npcIdRawNum")]
    pub npc_id_raw_num: i64,

    #[serde(rename = "mainQuestIdRawNum")]
    pub main_quest_id_raw_num: i64,

    #[serde(rename = "priorityRawNum")]
    pub priority_raw_num: i64,

    #[serde(rename = "isAuto")]
    pub is_auto: Option<bool>,
}

pub fn load() -> Result<CoopInteractionExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "CoopInteractionExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
