/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type CoopPointExcelConfigData = Vec<CoopPointExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CoopPointExcelConfigDatum {
    pub id: i64,
    pub chapter_id: i64,
    #[serde(rename = "type")]
    pub coop_point_excel_config_datum_type: Type,
    pub accept_quest: Option<i64>,
    pub post_point_list: Vec<i64>,
    pub point_name_text_map_hash: i64,
    pub point_dec_text_map_hash: i64,
    pub point_pos_id: i64,
    pub photo_male_hash: Option<f64>,
    pub photo_female_hash: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Type {
    #[serde(rename = "POINT_END")]
    PointEnd,
    #[serde(rename = "POINT_MIDDLE")]
    PointMiddle,
    #[serde(rename = "POINT_START")]
    PointStart,
}
