// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type CusmtomGadgetConfigIdExcelConfigData = Vec<CusmtomGadgetConfigIdExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct CusmtomGadgetConfigIdExcelConfigDatum {
    #[serde(rename = "configId")]
    pub config_id: i64,

    #[serde(rename = "itemId")]
    pub item_id: i64,

    #[serde(rename = "gadgetId")]
    pub gadget_id: i64,

    #[serde(rename = "NHMDAFPJICP")]
    pub nhmdafpjicp: i64,

    #[serde(rename = "EOEEOCIHPGP")]
    pub eoeeocihpgp: i64,
}

pub fn load() -> Result<CusmtomGadgetConfigIdExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "CusmtomGadgetConfigIdExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
