// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type CusmtomGadgetSlotExcelConfigData = Vec<CusmtomGadgetSlotExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct CusmtomGadgetSlotExcelConfigDatum {
    #[serde(rename = "PGGCMGMPMGM")]
    pub pggcmgmpmgm: i64,

    #[serde(rename = "KDMHJBOONFO")]
    pub kdmhjboonfo: Vec<i64>,

    #[serde(rename = "OCAPFCLGOHG")]
    pub ocapfclgohg: Option<bool>,

    #[serde(rename = "DEDGCDDHEMD")]
    pub dedgcddhemd: Vec<i64>,

    #[serde(rename = "EJKEFALJHPG")]
    pub ejkefaljhpg: Vec<i64>,

    #[serde(rename = "CLGMIJIANHI")]
    pub clgmijianhi: Option<i64>,
}

pub fn load() -> Result<CusmtomGadgetSlotExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "CusmtomGadgetSlotExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
