/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type CusmtomGadgetConfigIdExcelConfigData = Vec<CusmtomGadgetConfigIdExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CusmtomGadgetConfigIdExcelConfigDatum {
    pub config_id: i64,
    pub item_id: i64,
    pub gadget_id: i64,
    #[serde(rename = "PBJLLONOJBD")]
    pub pbjllonojbd: i64,
    #[serde(rename = "HCKINPJMFPE")]
    pub hckinpjmfpe: i64,
}
