/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type CustomGadgetRootExcelConfigData = Vec<CustomGadgetRootExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct CustomGadgetRootExcelConfigDatum {
    #[serde(rename = "rootGadgetID")]
    pub root_gadget_id: i64,
    pub custom_gadget_type: String,
    pub page_title: PageTitle,
    pub recommend_config: String,
    pub tab_list: Vec<i64>,
    pub dither_gadget_config_id_list: Vec<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PageTitle {
    #[serde(rename = "UI_HOMEWORLD_CHANGE_MOUNTAIN_BUTTON")]
    UiHomeworldChangeMountainButton,
    #[serde(rename = "UI_HOMEWORLD_CUSTOM_BUTTON")]
    UiHomeworldCustomButton,
    #[serde(rename = "UI_HOMEWORLD_CUSTOM_LNLWOODCUT")]
    UiHomeworldCustomLnlwoodcut,
    #[serde(rename = "UI_HOMEWORLD_CUSTOM_MINIASCAPE")]
    UiHomeworldCustomMiniascape,
    #[serde(rename = "UI_HOMEWORLD_CUSTOM_SNOWMANBUTTON")]
    UiHomeworldCustomSnowmanbutton,
    #[serde(rename = "UI_HOMEWORLD_CUSTOM_VINTAGESTALL")]
    UiHomeworldCustomVintagestall,
}
