/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type CustomLevelDungeonConfigData = Vec<CustomLevelDungeonConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct CustomLevelDungeonConfigDatum {
    #[serde(rename = "dungeonID")]
    pub dungeon_id: i64,
    #[serde(rename = "order")]
    pub order: i64,
    #[serde(rename = "jsonPath")]
    pub json_path: String,
    pub jdpcngpcljc: String,
    pub ljjoiofdfei: Option<f64>,
    pub fpgpeeijhpc: Option<f64>,
    pub hfegnechenf: i64,
    pub kpljphpmgpf: i64,
    pub lfknlhfjkcn: String,
    pub cccinldbfdl: Vec<i64>,
}
