// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type DailyDungeonConfigData = Vec<DailyDungeonConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct DailyDungeonConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "monday")]
    pub monday: Vec<i64>,

    #[serde(rename = "tuesday")]
    pub tuesday: Vec<i64>,

    #[serde(rename = "wednesday")]
    pub wednesday: Vec<i64>,

    #[serde(rename = "thursday")]
    pub thursday: Vec<i64>,

    #[serde(rename = "friday")]
    pub friday: Vec<i64>,

    #[serde(rename = "saturday")]
    pub saturday: Vec<i64>,

    #[serde(rename = "sunday")]
    pub sunday: Vec<i64>,
}

pub fn load() -> Result<DailyDungeonConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "DailyDungeonConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
