// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type DeshretPoiCatalogDataData = Vec<DeshretPoiCatalogDataDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct DeshretPoiCatalogDataDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "BGBGLKCCFFI")]
    pub bgbglkccffi: i64,

    #[serde(rename = "titleTextMapHash")]
    pub title_text_map_hash: i64,

    #[serde(rename = "icon")]
    pub icon: String,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,

    #[serde(rename = "HJOCPPAFKGJ")]
    pub hjocppafkgj: i64,

    #[serde(rename = "IIBLFGOGFAN")]
    pub iiblfgogfan: i64,

    #[serde(rename = "FJHPDAHPBBL")]
    pub fjhpdahpbbl: i64,
}

pub fn load() -> Result<DeshretPoiCatalogDataData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "DeshretPoiCatalogDataData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
