/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type DialogExcelConfigData = Vec<DialogExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DialogExcelConfigDatum {
    #[serde(rename = "GFLDJMJKIKE")]
    pub gfldjmjkike: i64,
    pub next_dialogs: Vec<i64>,
    pub talk_role: TalkRole,
    pub talk_content_text_map_hash: i64,
    pub talk_title_text_map_hash: i64,
    pub talk_role_name_text_map_hash: i64,
    pub talk_asset_path: String,
    pub talk_asset_path_alter: String,
    pub talk_audio_name: String,
    pub action_before: ActionBefore,
    pub action_while: ActionWhile,
    pub action_after: String,
    pub option_icon: OptionIcon,
    pub talk_show_type: Option<TalkShowType>,
    pub group_id: Option<i64>,
    pub show_duration: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActionBefore {
    #[serde(rename = "default_empty")]
    DefaultEmpty,
    #[serde(rename = "DialogAction/D220410303_Before")]
    DialogActionD220410303Before,
    #[serde(rename = "DialogAction/D230260204_After")]
    DialogActionD230260204After,
    #[serde(rename = "DialogAction/D230260206_After")]
    DialogActionD230260206After,
    #[serde(rename = "DialogAction/D230430129_Before")]
    DialogActionD230430129Before,
    #[serde(rename = "DialogAction/D230430130_Before")]
    DialogActionD230430130Before,
    #[serde(rename = "DialogAction/D230431702_Before")]
    DialogActionD230431702Before,
    #[serde(rename = "DialogAction/D400880401_While")]
    DialogActionD400880401While,
    #[serde(rename = "DialogAction/D710600101_After")]
    DialogActionD710600101After,
    #[serde(rename = "DialogAction/D710790102_Before")]
    DialogActionD710790102Before,
    #[serde(rename = "DialogAction/D710790202_Before")]
    DialogActionD710790202Before,
    #[serde(rename = "DialogAction/D710790302_Before")]
    DialogActionD710790302Before,
    #[serde(rename = "DialogAction/D710790402_Before")]
    DialogActionD710790402Before,
    #[serde(rename = "DialogAction/D710790502_Before")]
    DialogActionD710790502Before,
    #[serde(rename = "DialogAction/D710790602_Before")]
    DialogActionD710790602Before,
    #[serde(rename = "DialogAction/D710790702_Before")]
    DialogActionD710790702Before,
    #[serde(rename = "DialogAction/D710790802_Before")]
    DialogActionD710790802Before,
    #[serde(rename = "DialogAction/D710790902_Before")]
    DialogActionD710790902Before,
    #[serde(rename = "DialogAction/D710791002_Before")]
    DialogActionD710791002Before,
    #[serde(rename = "DialogAction/D710791102_Before")]
    DialogActionD710791102Before,
    #[serde(rename = "DialogAction/D710791202_Before")]
    DialogActionD710791202Before,
    #[serde(rename = "DialogAction/D721490201_Before.json")]
    DialogActionD721490201BeforeJson,
    #[serde(rename = "DialogAction/D721490301_Before.json")]
    DialogActionD721490301BeforeJson,
    #[serde(rename = "DialogAction/D721510101_Before.json")]
    DialogActionD721510101BeforeJson,
    #[serde(rename = "DialogAction/D721510401_Before.json")]
    DialogActionD721510401BeforeJson,
    #[serde(rename = "DialogAction/D721510701_Before.json")]
    DialogActionD721510701BeforeJson,
    #[serde(rename = "DialogAction/D736890105_Before")]
    DialogActionD736890105Before,
    #[serde(rename = "DialogAction/D746680101_Before")]
    DialogActionD746680101Before,
    #[serde(rename = "DialogAction/Nutcracker_LerpIn")]
    DialogActionNutcrackerLerpIn,
    #[serde(rename = "DialogAction/Nutcracker_LerpIn_Paimon")]
    DialogActionNutcrackerLerpInPaimon,
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "GCG/ClearWorldChallengeTalk")]
    GcgClearWorldChallengeTalk,
    #[serde(rename = "GCG/ClearWorldChallengeTalk_CatBar")]
    GcgClearWorldChallengeTalkCatBar,
    #[serde(rename = "GCG/ClearWorldChallengeTalk_Nosteer")]
    GcgClearWorldChallengeTalkNosteer,
    #[serde(rename = "GCG/Gcg_Invitation_End")]
    GcgGcgInvitationEnd,
    #[serde(rename = "GCG/open_GcgBossChallengesPage")]
    GcgOpenGcgBossChallengesPage,
    #[serde(rename = "GCG/open_GcgCardSettingPage")]
    GcgOpenGcgCardSettingPage,
    #[serde(rename = "GCG/open_GcgLevelPage")]
    GcgOpenGcgLevelPage,
    #[serde(rename = "GCG/open_GcgLevelPage_CatBar_1")]
    GcgOpenGcgLevelPageCatBar1,
    #[serde(rename = "GCG/open_GcgLevelPage_Invitation")]
    GcgOpenGcgLevelPageInvitation,
    #[serde(rename = "GCG/open_GcgLevelPage_Invitation_End")]
    GcgOpenGcgLevelPageInvitationEnd,
    #[serde(rename = "GCG/open_GcgLevelPage_Invitation_Start")]
    GcgOpenGcgLevelPageInvitationStart,
    #[serde(rename = "GCG/open_GcgPlayerLevelPage")]
    GcgOpenGcgPlayerLevelPage,
    #[serde(rename = "GCG/open_GcgPVEInfinitePage")]
    GcgOpenGcgPveInfinitePage,
    #[serde(rename = "GCG/open_GcgPvePage")]
    GcgOpenGcgPvePage,
    #[serde(rename = "GCG/open_GcgPVEPuzzlePage")]
    GcgOpenGcgPvePuzzlePage,
    #[serde(rename = "GCG/open_GcgReplayPage")]
    GcgOpenGcgReplayPage,
    #[serde(rename = "GCG/open_GcgShopPage")]
    GcgOpenGcgShopPage,
    #[serde(rename = "GCG/open_Ggccard_page")]
    GcgOpenGgccardPage,
    #[serde(rename = "GCG/Prince_Start")]
    GcgPrinceStart,
    #[serde(rename = "HomeWorld/huling_bansleep")]
    HomeWorldHulingBansleep,
    #[serde(rename = "HomeWorld/huling_start")]
    HomeWorldHulingStart,
    #[serde(rename = "QuestDialogue/IQ/Inazuma_22014/Q2201401")]
    QuestDialogueIqInazuma22014Q2201401,
    #[serde(rename = "SimpleTalk/Akimbo")]
    SimpleTalkAkimbo,
    #[serde(rename = "SimpleTalk/Akimbo_Start")]
    SimpleTalkAkimboStart,
    #[serde(rename = "SimpleTalk/ChildCoverEye")]
    SimpleTalkChildCoverEye,
    #[serde(rename = "SimpleTalk/Confuse")]
    SimpleTalkConfuse,
    #[serde(rename = "SimpleTalk/Confuse_Start")]
    SimpleTalkConfuseStart,
    #[serde(rename = "SimpleTalk/Downcast")]
    SimpleTalkDowncast,
    #[serde(rename = "SimpleTalk/Downcast_Start")]
    SimpleTalkDowncastStart,
    #[serde(rename = "SimpleTalk/Greet")]
    SimpleTalkGreet,
    #[serde(rename = "SimpleTalk/Greet_Start")]
    SimpleTalkGreetStart,
    #[serde(rename = "SimpleTalk/Happy_Start")]
    SimpleTalkHappyStart,
    #[serde(rename = "SimpleTalk/HoldArm")]
    SimpleTalkHoldArm,
    #[serde(rename = "SimpleTalk/HoldHead")]
    SimpleTalkHoldHead,
    #[serde(rename = "SimpleTalk/HoldHead_Start")]
    SimpleTalkHoldHeadStart,
    #[serde(rename = "SimpleTalk/LerpInNpcLookAtOnly_Start")]
    SimpleTalkLerpInNpcLookAtOnlyStart,
    #[serde(rename = "SimpleTalk/LerpInNpcNoSteer_Start")]
    SimpleTalkLerpInNpcNoSteerStart,
    #[serde(rename = "SimpleTalk/NodHead")]
    SimpleTalkNodHead,
    #[serde(rename = "SimpleTalk/PaimonInTalk_Start")]
    SimpleTalkPaimonInTalkStart,
    #[serde(rename = "SimpleTalk/PaimonTalkPlus_Start")]
    SimpleTalkPaimonTalkPlusStart,
    #[serde(rename = "SimpleTalk/PutHand")]
    SimpleTalkPutHand,
    #[serde(rename = "SimpleTalk/RandomTalk")]
    SimpleTalkRandomTalk,
    #[serde(rename = "SimpleTalk/RandomTalkHold")]
    SimpleTalkRandomTalkHold,
    #[serde(rename = "SimpleTalk/RandomTalkHold_Start")]
    SimpleTalkRandomTalkHoldStart,
    #[serde(rename = "SimpleTalk/RandomTalk_Start")]
    SimpleTalkRandomTalkStart,
    #[serde(rename = "SimpleTalk/Refuse")]
    SimpleTalkRefuse,
    #[serde(rename = "SimpleTalk/Request01_Start")]
    SimpleTalkRequest01Start,
    #[serde(rename = "SimpleTalk/ShakeHead")]
    SimpleTalkShakeHead,
    #[serde(rename = "SimpleTalk/Shrug")]
    SimpleTalkShrug,
    #[serde(rename = "SimpleTalk/Shy")]
    SimpleTalkShy,
    #[serde(rename = "SimpleTalk/Standby")]
    SimpleTalkStandby,
    #[serde(rename = "SimpleTalk/SteerOnly")]
    SimpleTalkSteerOnly,
    #[serde(rename = "SimpleTalk/StrikeChest")]
    SimpleTalkStrikeChest,
    #[serde(rename = "SimpleTalk/StrikeChest_Start")]
    SimpleTalkStrikeChestStart,
    #[serde(rename = "SimpleTalk/Think")]
    SimpleTalkThink,
    #[serde(rename = "SimpleTalk/Think_Start")]
    SimpleTalkThinkStart,
    #[serde(rename = "TEST/CutToPaimon1")]
    TestCutToPaimon1,
    #[serde(rename = "TEST/EmojiBubble_Insight")]
    TestEmojiBubbleInsight,
    #[serde(rename = "TEST/EmojiBubble_Thinking")]
    TestEmojiBubbleThinking,
    #[serde(rename = "TEST/FadeToBlack")]
    TestFadeToBlack,
    #[serde(rename = "TEST/LerpInLady")]
    TestLerpInLady,
    #[serde(rename = "TEST/LerpInMale")]
    TestLerpInMale,
    #[serde(rename = "TEST/LerpInNpc")]
    TestLerpInNpc,
    #[serde(rename = "TEST/LerpInNpcExitFreestyle")]
    TestLerpInNpcExitFreestyle,
    #[serde(rename = "TEST/LerpInNpcExitFreestyleDelay")]
    TestLerpInNpcExitFreestyleDelay,
    #[serde(rename = "TEST/LerpInNpcLookAtOnly")]
    TestLerpInNpcLookAtOnly,
    #[serde(rename = "TEST/LerpInNpcNoSteer")]
    TestLerpInNpcNoSteer,
    #[serde(rename = "TEST/LerpInNpcSteer")]
    TestLerpInNpcSteer,
    #[serde(rename = "TEST/LerpInPaimon")]
    TestLerpInPaimon,
    #[serde(rename = "TEST/LerpInPaimonFirstCutscene")]
    TestLerpInPaimonFirstCutscene,
    #[serde(rename = "TEST/LerpInPaimon_TalkTest")]
    TestLerpInPaimonTalkTest,
    #[serde(rename = "TEST/LerpInQueen")]
    TestLerpInQueen,
    #[serde(rename = "TEST/LerpInQueenDefault")]
    TestLerpInQueenDefault,
    #[serde(rename = "TEST/LerplnNpcSteer")]
    TestLerplnNpcSteer,
    #[serde(rename = "TEST/Lua_10112_1")]
    TestLua10112_1,
    #[serde(rename = "TEST/Lua_10112_2")]
    TestLua10112_2,
    #[serde(rename = "TEST/Lua_10112_3")]
    TestLua10112_3,
    #[serde(rename = "TEST/Lua_20037_1")]
    TestLua20037_1,
    #[serde(rename = "TEST/Lua_20037_2")]
    TestLua20037_2,
    #[serde(rename = "TEST/Lua_20043_1")]
    TestLua20043_1,
    #[serde(rename = "TEST/Lua_20043_2")]
    TestLua20043_2,
    #[serde(rename = "TEST/Lua_20043_3")]
    TestLua20043_3,
    #[serde(rename = "TEST/Lua_20043_4")]
    TestLua20043_4,
    #[serde(rename = "TEST/Lua_20058_1")]
    TestLua20058_1,
    #[serde(rename = "TEST/Lua_22027_1")]
    TestLua22027_1,
    #[serde(rename = "TEST/Lua_22116_1")]
    TestLua22116_1,
    #[serde(rename = "TEST/Lua_22302_1")]
    TestLua22302_1,
    #[serde(rename = "TEST/Readable01")]
    TestReadable01,
    #[serde(rename = "TEST/TestTalk4")]
    TestTestTalk4,
    #[serde(rename = "UI/open_activity_brickbreaker_dungeonstart")]
    UiOpenActivityBrickbreakerDungeonstart,
    #[serde(rename = "UI/open_activity_brickbreaker_questlevelpage")]
    UiOpenActivityBrickbreakerQuestlevelpage,
    #[serde(rename = "UI/open_activity_brickbreaker_stageselectpage")]
    UiOpenActivityBrickbreakerStageselectpage,
    #[serde(rename = "UI/open_homeworld_build_page")]
    UiOpenHomeworldBuildPage,
    #[serde(rename = "UI/open_homeworld_level_page")]
    UiOpenHomeworldLevelPage,
    #[serde(rename = "UI/open_homeworld_shop_page")]
    UiOpenHomeworldShopPage,
    #[serde(rename = "UI/open_homeworld_switch_page")]
    UiOpenHomeworldSwitchPage,
    #[serde(rename = "UI/open_teyvatcard_setting_page")]
    UiOpenTeyvatcardSettingPage,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "snake_case")]
pub enum ActionWhile {
    #[serde(rename = "DialogAction/D200030101_While")]
    DialogActionD200030101While,
    #[serde(rename = "DialogAction/D200030104_While")]
    DialogActionD200030104While,
    #[serde(rename = "DialogAction/D200030113_While")]
    DialogActionD200030113While,
    #[serde(rename = "DialogAction/D200030301_While")]
    DialogActionD200030301While,
    #[serde(rename = "DialogAction/D200030302_While")]
    DialogActionD200030302While,
    #[serde(rename = "DialogAction/D200290101_While")]
    DialogActionD200290101While,
    #[serde(rename = "DialogAction/D200290703_While")]
    DialogActionD200290703While,
    #[serde(rename = "DialogAction/D230250601_While")]
    DialogActionD230250601While,
    #[serde(rename = "DialogAction/D230250901_While")]
    DialogActionD230250901While,
    #[serde(rename = "DialogAction/D230430201_While")]
    DialogActionD230430201While,
    #[serde(rename = "DialogAction/D230430507_While")]
    DialogActionD230430507While,
    #[serde(rename = "DialogAction/D230430509_While")]
    DialogActionD230430509While,
    #[serde(rename = "DialogAction/D230430908_While")]
    DialogActionD230430908While,
    #[serde(rename = "DialogAction/D230430910_While")]
    DialogActionD230430910While,
    #[serde(rename = "DialogAction/D230431604_While")]
    DialogActionD230431604While,
    #[serde(rename = "DialogAction/D400881401_While")]
    DialogActionD400881401While,
    #[serde(rename = "DialogAction/D400890509_While")]
    DialogActionD400890509While,
    #[serde(rename = "DialogAction/D400890512_While")]
    DialogActionD400890512While,
    #[serde(rename = "DialogAction/D400890611_While")]
    DialogActionD400890611While,
    #[serde(rename = "DialogAction/D400890715_While")]
    DialogActionD400890715While,
    #[serde(rename = "DialogAction/D400900307_While")]
    DialogActionD400900307While,
    #[serde(rename = "DialogAction/D400900310_While")]
    DialogActionD400900310While,
    #[serde(rename = "DialogAction/D400900414_While")]
    DialogActionD400900414While,
    #[serde(rename = "DialogAction/D400900512_While")]
    DialogActionD400900512While,
    #[serde(rename = "DialogAction/D680180801_While")]
    DialogActionD680180801While,
    #[serde(rename = "DialogAction/D680180902_While")]
    DialogActionD680180902While,
    #[serde(rename = "DialogAction/D680181102_While")]
    DialogActionD680181102While,
    #[serde(rename = "DialogAction/D680181202_While")]
    DialogActionD680181202While,
    #[serde(rename = "DialogAction/D727290101_While")]
    DialogActionD727290101While,
    #[serde(rename = "DialogAction/D746680113_While")]
    DialogActionD746680113While,
    #[serde(rename = "DialogAction/D746680117_While")]
    DialogActionD746680117While,
    #[serde(rename = "DialogAction/D746680121_While")]
    DialogActionD746680121While,
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "GCG/Prince_Continue")]
    GcgPrinceContinue,
    #[serde(rename = "GCG/RefreshCardGroupName")]
    GcgRefreshCardGroupName,
    #[serde(rename = "HomeWorld/huling_start")]
    HomeWorldHulingStart,
    #[serde(rename = "Quest_MQ354_ShowFeather")]
    QuestMq354ShowFeather,
    Rt,
    #[serde(rename = "SimpleTalk/Agree")]
    SimpleTalkAgree,
    #[serde(rename = "SimpleTalk/Akimbo")]
    SimpleTalkAkimbo,
    #[serde(rename = "SimpleTalk/Akimbo_Start")]
    SimpleTalkAkimboStart,
    #[serde(rename = "SimpleTalk/CLap_Start")]
    SimpleTalkCLapStart,
    #[serde(rename = "SimpleTalk/ChildCoverEye")]
    SimpleTalkChildCoverEye,
    #[serde(rename = "SimpleTalk/Clap")]
    SimpleTalkClap,
    #[serde(rename = "SimpleTalk/Confuse")]
    SimpleTalkConfuse,
    #[serde(rename = "SimpleTalk/Confuse_Start")]
    SimpleTalkConfuseStart,
    #[serde(rename = "SimpleTalk/Downcast")]
    SimpleTalkDowncast,
    #[serde(rename = "SimpleTalk/Downcast_Start")]
    SimpleTalkDowncastStart,
    #[serde(rename = "SimpleTalk/Foreke")]
    SimpleTalkForeke,
    #[serde(rename = "SimpleTalk/Forerke")]
    SimpleTalkForerke,
    #[serde(rename = "SimpleTalk/Forerke_Start")]
    SimpleTalkForerkeStart,
    #[serde(rename = "SimpleTalk/Greet")]
    SimpleTalkGreet,
    #[serde(rename = "SimpleTalk/Greet_Start")]
    SimpleTalkGreetStart,
    #[serde(rename = "SimpleTalk/Happy")]
    SimpleTalkHappy,
    #[serde(rename = "SimpleTalk/HoldAram")]
    SimpleTalkHoldAram,
    #[serde(rename = "SimpleTalk/HoldAram_Start")]
    SimpleTalkHoldAramStart,
    #[serde(rename = "SimpleTalk/HoldArm")]
    SimpleTalkHoldArm,
    #[serde(rename = "SimpleTalk/HoldArm_Start")]
    SimpleTalkHoldArmStart,
    #[serde(rename = "SimpleTalk/HoldHead")]
    SimpleTalkHoldHead,
    #[serde(rename = "SimpleTalk/HoldHead_Start")]
    SimpleTalkHoldHeadStart,
    #[serde(rename = "SimpleTalk/Idle_End")]
    SimpleTalkIdleEnd,
    #[serde(rename = "SimpleTalk/LerpInNpcDailyTalk_Start")]
    SimpleTalkLerpInNpcDailyTalkStart,
    #[serde(rename = "SimpleTalk/LerpInNpcNoSteer_Start")]
    SimpleTalkLerpInNpcNoSteerStart,
    #[serde(rename = "SimpleTalk/NodHead")]
    SimpleTalkNodHead,
    #[serde(rename = "SimpleTalk/NpcDailyTalkRandomFS")]
    SimpleTalkNpcDailyTalkRandomFs,
    #[serde(rename = "SimpleTalk/PutHand")]
    SimpleTalkPutHand,
    #[serde(rename = "SimpleTalk/RandomTalk")]
    SimpleTalkRandomTalk,
    #[serde(rename = "SimpleTalk/RandomTalkHold")]
    SimpleTalkRandomTalkHold,
    #[serde(rename = "SimpleTalk/RandomTalkHold_Start")]
    SimpleTalkRandomTalkHoldStart,
    #[serde(rename = "SimpleTalk/RandomTalk_Start")]
    SimpleTalkRandomTalkStart,
    #[serde(rename = "SimpleTalk/Refuse")]
    SimpleTalkRefuse,
    #[serde(rename = "SimpleTalk/Refuse_Start")]
    SimpleTalkRefuseStart,
    #[serde(rename = "SimpleTalk/Request01")]
    SimpleTalkRequest01,
    #[serde(rename = "SimpleTalk/Request01_Start")]
    SimpleTalkRequest01Start,
    #[serde(rename = "SimpleTalk/ShakeHead")]
    SimpleTalkShakeHead,
    #[serde(rename = "SimpleTalk/Shrug")]
    SimpleTalkShrug,
    #[serde(rename = "SimpleTalk/Shrug_Start")]
    SimpleTalkShrugStart,
    #[serde(rename = "SimpleTalk/Shy")]
    SimpleTalkShy,
    #[serde(rename = "SimpleTalk/Shy_Start")]
    SimpleTalkShyStart,
    #[serde(rename = "SimpleTalk/Sit01_Start")]
    SimpleTalkSit01Start,
    #[serde(rename = "SimpleTalk/SitHoldArm")]
    SimpleTalkSitHoldArm,
    #[serde(rename = "SimpleTalk/SitHoldArmHand")]
    SimpleTalkSitHoldArmHand,
    #[serde(rename = "SimpleTalk/SitHoldArm_Start")]
    SimpleTalkSitHoldArmStart,
    #[serde(rename = "SimpleTalk/SitPutArm")]
    SimpleTalkSitPutArm,
    #[serde(rename = "SimpleTalk/SitPutArm_Start")]
    SimpleTalkSitPutArmStart,
    #[serde(rename = "SimpleTalk/Standby")]
    SimpleTalkStandby,
    #[serde(rename = "SimpleTalk/SteerOnly")]
    SimpleTalkSteerOnly,
    #[serde(rename = "SimpleTalk/StrikeChest")]
    SimpleTalkStrikeChest,
    #[serde(rename = "SimpleTalk/StrikeChest_Start")]
    SimpleTalkStrikeChestStart,
    #[serde(rename = "SimpleTalk/Think")]
    SimpleTalkThink,
    #[serde(rename = "SimpleTalk/Think_Start")]
    SimpleTalkThinkStart,
    #[serde(rename = "SimpleTalk/VapourBird_Show02")]
    SimpleTalkVapourBirdShow02,
    #[serde(rename = "SimpleTalk/VapourBird_Show03")]
    SimpleTalkVapourBirdShow03,
    #[serde(rename = "SimpleTalk/VapourBird_Talk01_Start")]
    SimpleTalkVapourBirdTalk01Start,
    #[serde(rename = "TEST/BodyLang_Guard")]
    TestBodyLangGuard,
    #[serde(rename = "TEST/BodyLang_Standby")]
    TestBodyLangStandby,
    #[serde(rename = "TEST/D200490101")]
    TestD200490101,
    #[serde(rename = "TEST/D700080113")]
    TestD700080113,
    #[serde(rename = "TEST/D700080117")]
    TestD700080117,
    #[serde(rename = "TEST/EchoConchShowEff")]
    TestEchoConchShowEff,
    #[serde(rename = "TEST/EmojiBubble_Afraid")]
    TestEmojiBubbleAfraid,
    #[serde(rename = "TEST/EmojiBubble_Angry")]
    TestEmojiBubbleAngry,
    #[serde(rename = "TEST/EmojiBubble_Awkward")]
    TestEmojiBubbleAwkward,
    #[serde(rename = "TEST/EmojiBubble_Exciting")]
    TestEmojiBubbleExciting,
    #[serde(rename = "TEST/EmojiBubble_Happy")]
    TestEmojiBubbleHappy,
    #[serde(rename = "TEST/EmojiBubble_Insight")]
    TestEmojiBubbleInsight,
    #[serde(rename = "TEST/EmojiBubble_Love")]
    TestEmojiBubbleLove,
    #[serde(rename = "TEST/EmojiBubble_Query")]
    TestEmojiBubbleQuery,
    #[serde(rename = "TEST/EmojiBubble_Sad")]
    TestEmojiBubbleSad,
    #[serde(rename = "TEST/EmojiBubble_Surprise")]
    TestEmojiBubbleSurprise,
    #[serde(rename = "TEST/EmojiBubble_Sweat")]
    TestEmojiBubbleSweat,
    #[serde(rename = "TEST/EmojiBubble_Thinking")]
    TestEmojiBubbleThinking,
    #[serde(rename = "TEST/EmojiBubble_Worry")]
    TestEmojiBubbleWorry,
    #[serde(rename = "TEST/LerpInNpc")]
    TestLerpInNpc,
    #[serde(rename = "TEST/LerpInNpcLookAtOnly")]
    TestLerpInNpcLookAtOnly,
    #[serde(rename = "TEST/LerpInNpcNoSteer")]
    TestLerpInNpcNoSteer,
    #[serde(rename = "TEST/LerpOutNpcNoSteer")]
    TestLerpOutNpcNoSteer,
    #[serde(rename = "TEST/Lua_10100_5")]
    TestLua10100_5,
    #[serde(rename = "TEST/Lua_10100_6")]
    TestLua10100_6,
    #[serde(rename = "TEST/Lua_10100_7")]
    TestLua10100_7,
    #[serde(rename = "TEST/Lua_10501_1")]
    TestLua10501_1,
    #[serde(rename = "TEST/Lua_10501_2")]
    TestLua10501_2,
    #[serde(rename = "TEST/Lua_10501_3")]
    TestLua10501_3,
    #[serde(rename = "TEST/Lua_10501_4")]
    TestLua10501_4,
    #[serde(rename = "TEST/Lua_11101_1")]
    TestLua11101_1,
    #[serde(rename = "TEST/Lua_11101_2")]
    TestLua11101_2,
    #[serde(rename = "TEST/Lua_11101_3")]
    TestLua11101_3,
    #[serde(rename = "TEST/Lua_20040_1")]
    TestLua20040_1,
    #[serde(rename = "TEST/Lua_20040_2")]
    TestLua20040_2,
    #[serde(rename = "TEST/Lua_20040_3")]
    TestLua20040_3,
    #[serde(rename = "TEST/Lua_20051_1")]
    TestLua20051_1,
    #[serde(rename = "TEST/Lua_20054_1")]
    TestLua20054_1,
    #[serde(rename = "TEST/Lua_20054_2")]
    TestLua20054_2,
    #[serde(rename = "TEST/Lua_20062_1")]
    TestLua20062_1,
    #[serde(rename = "TEST/Lua_20062_2")]
    TestLua20062_2,
    #[serde(rename = "TEST/Lua_20062_3")]
    TestLua20062_3,
    #[serde(rename = "TEST/Lua_20062_4")]
    TestLua20062_4,
    #[serde(rename = "TEST/Lua_20101_1")]
    TestLua20101_1,
    #[serde(rename = "TEST/Lua_20101_11")]
    TestLua20101_11,
    #[serde(rename = "TEST/Lua_20101_11A")]
    TestLua20101_11A,
    #[serde(rename = "TEST/Lua_20101_11B")]
    TestLua20101_11B,
    #[serde(rename = "TEST/Lua_20101_11C")]
    TestLua20101_11C,
    #[serde(rename = "TEST/Lua_20101_11X")]
    TestLua20101_11X,
    #[serde(rename = "TEST/Lua_20101_12")]
    TestLua20101_12,
    #[serde(rename = "TEST/Lua_20101_13")]
    TestLua20101_13,
    #[serde(rename = "TEST/Lua_20101_1A")]
    TestLua20101_1A,
    #[serde(rename = "TEST/Lua_20101_1B")]
    TestLua20101_1B,
    #[serde(rename = "TEST/Lua_20101_1C")]
    TestLua20101_1C,
    #[serde(rename = "TEST/Lua_20101_1X")]
    TestLua20101_1X,
    #[serde(rename = "TEST/Lua_20101_2")]
    TestLua20101_2,
    #[serde(rename = "TEST/Lua_20101_21")]
    TestLua20101_21,
    #[serde(rename = "TEST/Lua_20101_21A")]
    TestLua20101_21A,
    #[serde(rename = "TEST/Lua_20101_21B")]
    TestLua20101_21B,
    #[serde(rename = "TEST/Lua_20101_21C")]
    TestLua20101_21C,
    #[serde(rename = "TEST/Lua_20101_21X")]
    TestLua20101_21X,
    #[serde(rename = "TEST/Lua_20101_22")]
    TestLua20101_22,
    #[serde(rename = "TEST/Lua_20101_23")]
    TestLua20101_23,
    #[serde(rename = "TEST/Lua_20101_3")]
    TestLua20101_3,
    #[serde(rename = "TEST/Lua_20103_1")]
    TestLua20103_1,
    #[serde(rename = "TEST/Lua_20517_1")]
    TestLua20517_1,
    #[serde(rename = "TEST/Lua_22004_1")]
    TestLua22004_1,
    #[serde(rename = "TEST/Lua_22004_2")]
    TestLua22004_2,
    #[serde(rename = "TEST/Lua_22021_1")]
    TestLua22021_1,
    #[serde(rename = "TEST/Lua_22021_2")]
    TestLua22021_2,
    #[serde(rename = "TEST/Lua_22106_1")]
    TestLua22106_1,
    #[serde(rename = "TEST/Lua_22106_2")]
    TestLua22106_2,
    #[serde(rename = "TEST/Lua_22107_1")]
    TestLua22107_1,
    #[serde(rename = "TEST/Lua_22107_2")]
    TestLua22107_2,
    #[serde(rename = "TEST/Lua_22107_3")]
    TestLua22107_3,
    #[serde(rename = "TEST/Lua_22107_4")]
    TestLua22107_4,
    #[serde(rename = "TEST/Lua_22107_5")]
    TestLua22107_5,
    #[serde(rename = "TEST/Lua_22115_1")]
    TestLua22115_1,
    #[serde(rename = "TEST/Lua_41125_1")]
    TestLua41125_1,
    #[serde(rename = "TEST/Lua_41125_2")]
    TestLua41125_2,
    #[serde(rename = "TEST/Lua_41125_3")]
    TestLua41125_3,
    #[serde(rename = "TEST/Lua_41127_1")]
    TestLua41127_1,
    #[serde(rename = "TEST/Lua_41127_2")]
    TestLua41127_2,
    #[serde(rename = "TEST/Lua_41127_3")]
    TestLua41127_3,
    #[serde(rename = "TEST/Lua_426_1")]
    TestLua426_1,
    #[serde(rename = "TEST/Lua_464_3")]
    TestLua464_3,
    #[serde(rename = "TEST/Lua_465_10")]
    TestLua465_10,
    #[serde(rename = "TEST/Lua_466_1")]
    TestLua466_1,
    #[serde(rename = "TEST/Lua_466_2")]
    TestLua466_2,
    #[serde(rename = "TEST/Lua_466_5")]
    TestLua466_5,
    #[serde(rename = "TEST/Lua_466_6")]
    TestLua466_6,
    #[serde(rename = "TEST/Lua_466_7")]
    TestLua466_7,
    #[serde(rename = "TEST/Lua_466_8")]
    TestLua466_8,
    #[serde(rename = "TEST/Lua_467_1")]
    TestLua467_1,
    #[serde(rename = "TEST/Lua_487")]
    TestLua487,
    #[serde(rename = "TEST/Lua_70144_1")]
    TestLua70144_1,
    #[serde(rename = "TEST/Lua_71008_1")]
    TestLua71008_1,
    #[serde(rename = "TEST/Lua_71008_2")]
    TestLua71008_2,
    #[serde(rename = "TEST/Lua_71008_3")]
    TestLua71008_3,
    #[serde(rename = "TEST/Lua_71008_4")]
    TestLua71008_4,
    #[serde(rename = "TEST/Lua_71008_5")]
    TestLua71008_5,
    #[serde(rename = "TEST/RandomQuestLerpInNpc")]
    TestRandomQuestLerpInNpc,
    #[serde(rename = "TEST/TEST_Chest_Btn")]
    TestTestChestBtn,
    #[serde(rename = "UI/open_homeworld_level_page")]
    UiOpenHomeworldLevelPage,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum OptionIcon {
    #[serde(rename = "")]
    Empty,
    #[serde(rename = "UI_Icon_Intee_ActivityProps")]
    UiIconInteeActivityProps,
    #[serde(rename = "UI_Icon_Intee_AkaFes_Architect")]
    UiIconInteeAkaFesArchitect,
    #[serde(rename = "UI_Icon_Intee_AkaFes_Astrolabe")]
    UiIconInteeAkaFesAstrolabe,
    #[serde(rename = "UI_Icon_Intee_AkaFes_Reasoning")]
    UiIconInteeAkaFesReasoning,
    #[serde(rename = "UI_Icon_Intee_AkaFes_Rhythm")]
    UiIconInteeAkaFesRhythm,
    #[serde(rename = "UI_Icon_Intee_AreaUpgrad")]
    UiIconInteeAreaUpgrad,
    #[serde(rename = "UI_Icon_Intee_Astrology")]
    UiIconInteeAstrology,
    #[serde(rename = "UI_Icon_Intee_Blacksmith")]
    UiIconInteeBlacksmith,
    #[serde(rename = "UI_Icon_Intee_Blessing")]
    UiIconInteeBlessing,
    #[serde(rename = "UI_Icon_Intee_Comfort")]
    UiIconInteeComfort,
    #[serde(rename = "UI_Icon_Intee_DailyEvent_0")]
    UiIconInteeDailyEvent0,
    #[serde(rename = "UI_Icon_Intee_DailyEvent_1")]
    UiIconInteeDailyEvent1,
    #[serde(rename = "UI_Icon_Intee_DiceDungeon")]
    UiIconInteeDiceDungeon,
    #[serde(rename = "UI_Icon_Intee_ElectroherculesBattle")]
    UiIconInteeElectroherculesBattle,
    #[serde(rename = "UI_Icon_Intee_Explore_0")]
    UiIconInteeExplore0,
    #[serde(rename = "UI_Icon_Intee_Fishes")]
    UiIconInteeFishes,
    #[serde(rename = "UI_Icon_Intee_FlightChallenge")]
    UiIconInteeFlightChallenge,
    #[serde(rename = "UI_Icon_Intee_FungusFighter")]
    UiIconInteeFungusFighter,
    #[serde(rename = "UI_Icon_Intee_FungusFighterV2")]
    UiIconInteeFungusFighterV2,
    #[serde(rename = "UI_Icon_Intee_FurnitureBuild")]
    UiIconInteeFurnitureBuild,
    #[serde(rename = "UI_Icon_Intee_GcgJiuGuan")]
    UiIconInteeGcgJiuGuan,
    #[serde(rename = "UI_Icon_Intee_GcgPve")]
    UiIconInteeGcgPve,
    #[serde(rename = "UI_Icon_Intee_GcgWatchVideo")]
    UiIconInteeGcgWatchVideo,
    #[serde(rename = "UI_Icon_Intee_GcgZhanDou")]
    UiIconInteeGcgZhanDou,
    #[serde(rename = "UI_Icon_Intee_GcgZhanDou_01")]
    UiIconInteeGcgZhanDou01,
    #[serde(rename = "UI_Icon_Intee_GeneralCargo")]
    UiIconInteeGeneralCargo,
    #[serde(rename = "UI_Icon_Intee_GrowFlowers")]
    UiIconInteeGrowFlowers,
    #[serde(rename = "UI_Icon_Intee_HomeSwitch")]
    UiIconInteeHomeSwitch,
    #[serde(rename = "UI_Icon_Intee_LanV3BoatGame")]
    UiIconInteeLanV3BoatGame,
    #[serde(rename = "UI_Icon_Intee_LanV3Shadow")]
    UiIconInteeLanV3Shadow,
    #[serde(rename = "UI_Icon_Intee_LuminanceStone")]
    UiIconInteeLuminanceStone,
    #[serde(rename = "UI_Icon_Intee_Mechanism")]
    UiIconInteeMechanism,
    #[serde(rename = "UI_Icon_Intee_Miscsmarvs")]
    UiIconInteeMiscsmarvs,
    #[serde(rename = "UI_Icon_Intee_Music")]
    UiIconInteeMusic,
    #[serde(rename = "UI_Icon_Intee_Nutcracker01")]
    UiIconInteeNutcracker01,
    #[serde(rename = "UI_Icon_Intee_Nutcracker02")]
    UiIconInteeNutcracker02,
    #[serde(rename = "UI_Icon_Intee_Pacman")]
    UiIconInteePacman,
    #[serde(rename = "UI_Icon_Intee_PenAdvShuffleBoard")]
    UiIconInteePenAdvShuffleBoard,
    #[serde(rename = "UI_Icon_Intee_PenAdvTargetShooting")]
    UiIconInteePenAdvTargetShooting,
    #[serde(rename = "UI_Icon_Intee_PlayerLevel_0")]
    UiIconInteePlayerLevel0,
    #[serde(rename = "UI_Icon_Intee_Questevents")]
    UiIconInteeQuestevents,
    #[serde(rename = "UI_Icon_Intee_Questinference")]
    UiIconInteeQuestinference,
    #[serde(rename = "UI_Icon_Intee_Reputation")]
    UiIconInteeReputation,
    #[serde(rename = "UI_Icon_Intee_Restaurant")]
    UiIconInteeRestaurant,
    #[serde(rename = "UI_Icon_Intee_SandwormCannon")]
    UiIconInteeSandwormCannon,
    #[serde(rename = "UI_Icon_Intee_Shop")]
    UiIconInteeShop,
    #[serde(rename = "UI_Icon_Intee_Souvenir")]
    UiIconInteeSouvenir,
    #[serde(rename = "UI_Icon_Intee_Speedup")]
    UiIconInteeSpeedup,
    #[serde(rename = "UI_Icon_Intee_TalkSpecial")]
    UiIconInteeTalkSpecial,
    #[serde(rename = "UI_Icon_Intee_TheatreMechanicus")]
    UiIconInteeTheatreMechanicus,
    #[serde(rename = "UI_Icon_Intee_ToyBattleQTE")]
    UiIconInteeToyBattleQte,
    #[serde(rename = "UI_Icon_Intee_TreasureBox")]
    UiIconInteeTreasureBox,
    #[serde(rename = "UI_Icon_Intee_TreasureGift")]
    UiIconInteeTreasureGift,
    #[serde(rename = "UI_Icon_Intee_TreasureHunt")]
    UiIconInteeTreasureHunt,
    #[serde(rename = "UI_Icon_Intee_Vintage_01")]
    UiIconInteeVintage01,
    #[serde(rename = "UI_Icon_Intee_Vintage_02")]
    UiIconInteeVintage02,
    #[serde(rename = "UI_Icon_Intee_Vintage_03")]
    UiIconInteeVintage03,
    #[serde(rename = "UI_Icon_Quest_Once")]
    UiIconQuestOnce,
    #[serde(rename = "UI_NPCTopIcon_Activity_BrickBreaker")]
    UiNpcTopIconActivityBrickBreaker,
    #[serde(rename = "UI_NPCTopIcon_Activity_Music")]
    UiNpcTopIconActivityMusic,
    #[serde(rename = "UI_NPCTopIcon_Activity_ProjectionNPC")]
    UiNpcTopIconActivityProjectionNpc,
    #[serde(rename = "UI_NPCTopIcon_Activity_RobotGacha")]
    UiNpcTopIconActivityRobotGacha,
    #[serde(rename = "UI_NPCTopIcon_Blacksmith")]
    UiNpcTopIconBlacksmith,
    #[serde(rename = "UI_NPCTopIcon_Combine")]
    UiNpcTopIconCombine,
    #[serde(rename = "UI_NPCTopIcon_EditTeam")]
    UiNpcTopIconEditTeam,
    #[serde(rename = "UI_NPCTopIcon_MiscsMarvs")]
    UiNpcTopIconMiscsMarvs,
    #[serde(rename = "UI_NPCTopIcon_Restaurant")]
    UiNpcTopIconRestaurant,
    #[serde(rename = "UI_NPCTopIcon_Souvenir")]
    UiNpcTopIconSouvenir,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct TalkRole {
    #[serde(rename = "type")]
    pub talk_role_type: Option<Type>,
    pub id: String,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Type {
    #[serde(rename = "TALK_ROLE_BLACK_SCREEN")]
    TalkRoleBlackScreen,
    #[serde(rename = "TALK_ROLE_CONSEQUENT_BLACK_SCREEN")]
    TalkRoleConsequentBlackScreen,
    #[serde(rename = "TALK_ROLE_CONSEQUENT_NEED_CLICK_BLACK_SCREEN")]
    TalkRoleConsequentNeedClickBlackScreen,
    #[serde(rename = "TALK_ROLE_GADGET")]
    TalkRoleGadget,
    #[serde(rename = "TALK_ROLE_MATE_AVATAR")]
    TalkRoleMateAvatar,
    #[serde(rename = "TALK_ROLE_NEED_CLICK_BLACK_SCREEN")]
    TalkRoleNeedClickBlackScreen,
    #[serde(rename = "TALK_ROLE_NPC")]
    TalkRoleNpc,
    #[serde(rename = "TALK_ROLE_PLAYER")]
    TalkRolePlayer,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum TalkShowType {
    #[serde(rename = "TALK_SHOW_FORCE_SELECT")]
    TalkShowForceSelect,
}
