/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type DocumentExcelConfigData = Vec<DocumentExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct DocumentExcelConfigDatum {
    pub id: i64,
    pub title_text_map_hash: i64,
    pub content_localized_id: Option<i64>,
    pub preview_path: String,
    pub video_path: VideoPath,
    #[serde(rename = "CDFELBCMBEL")]
    pub cdfelbcmbel: Cdfelbcmbel,
    #[serde(rename = "BFGHHBPMMBC")]
    pub bfghhbpmmbc: Vec<i64>,
    #[serde(rename = "LJFGLIKINNB")]
    pub ljfglikinnb: Vec<i64>,
    #[serde(rename = "HHIINAIEAHO")]
    pub hhiinaieaho: Option<Hhiinaieaho>,
    pub document_type: Option<DocumentType>,
    #[serde(rename = "subtitleID")]
    pub subtitle_id: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Cdfelbcmbel {
    #[serde(rename = "ART/UI/Menus/Widget/Letter/Common_ReadDialog_Special_Bg")]
    ArtUiMenusWidgetLetterCommonReadDialogSpecialBg,
    #[serde(rename = "ART/UI/Menus/Widget/Letter/FleurFairV2_ReadDialog_Special_Bg")]
    ArtUiMenusWidgetLetterFleurFairV2ReadDialogSpecialBg,
    #[serde(rename = "")]
    Empty,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum DocumentType {
    Letter,
    Video,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Hhiinaieaho {
    #[serde(rename = "DOCUMENT_SPLIT_TYPE_BY_LINE")]
    DocumentSplitTypeByLine,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum VideoPath {
    #[serde(rename = "Ambor_Readings.usm")]
    AmborReadingsUsm,
    #[serde(rename = "")]
    Empty,
}
