// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type EffigyChallengeV2ExcelConfigData = Vec<EffigyChallengeV2ExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct EffigyChallengeV2ExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "dayIndex")]
    pub day_index: i64,

    #[serde(rename = "CJPHCAILPJM")]
    pub cjphcailpjm: i64,

    #[serde(rename = "NFECLGAGBBE")]
    pub nfeclgagbbe: Vec<i64>,

    #[serde(rename = "ALCMEFLGLGC")]
    pub alcmeflglgc: Vec<i64>,

    #[serde(rename = "FMGLPKPJIPC")]
    pub fmglpkpjipc: Vec<i64>,

    #[serde(rename = "BBJCMGJLEMA")]
    pub bbjcmgjlema: String,

    #[serde(rename = "IBFBCAAIMEN")]
    pub ibfbcaaimen: String,

    #[serde(rename = "EHIEJILAIEN")]
    pub ehiejilaien: i64,

    #[serde(rename = "EOIDBGBPDLH")]
    pub eoidbgbpdlh: Vec<i64>,

    #[serde(rename = "CJEAFOPJPGC")]
    pub cjeafopjpgc: Vec<i64>,

    #[serde(rename = "KOHJJFJEGBD")]
    pub kohjjfjegbd: Vec<i64>,

    #[serde(rename = "levelTitleTextMapHash")]
    pub level_title_text_map_hash: i64,

    #[serde(rename = "levelDescTextMapHash")]
    pub level_desc_text_map_hash: i64,

    #[serde(rename = "CGHDLPENPJF")]
    pub cghdlpenpjf: i64,

    #[serde(rename = "OJOKFBOIMGM")]
    pub ojokfboimgm: i64,
}

pub fn load() -> Result<EffigyChallengeV2ExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "EffigyChallengeV2ExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
