/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ElectroherculesBattleStageExcelConfigData = Vec<ElectroherculesBattleStageExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct ElectroherculesBattleStageExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "levelTitleTextMapHash")]
    pub level_title_text_map_hash: i64,
    pub pfnngmobflo: i64,
    #[serde(rename = "levelIdList")]
    pub level_id_list: Vec<i64>,
    #[serde(rename = "openTime")]
    pub open_time: i64,
    pub jdjdfbbbalj: i64,
    pub clclneompod: i64,
    pub fledljamcpj: String,
    pub aofgfchdonh: String,
    pub hgfbdfjkphc: String,
    #[serde(rename = "stageType")]
    pub stage_type: String,
    pub mgkcmagcbpm: i64,
    pub gbkkiigdmac: i64,
    #[serde(rename = "pushTipsId")]
    pub push_tips_id: Option<i64>,
    pub iocpiajmpko: Option<i64>,
}
