/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ElectroherculesBattleStageExcelConfigData = Vec<ElectroherculesBattleStageExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct ElectroherculesBattleStageExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "levelTitleTextMapHash")]
    pub level_title_text_map_hash: i64,
    pub pnahhedplje: i64,
    pub gikgnblpbcm: Vec<i64>,
    pub nckommfglpn: i64,
    pub bnofacifjan: i64,
    pub mkilmogjkho: i64,
    pub imdlfiomcpb: String,
    pub mibonmleofh: String,
    pub enlmbiopmoh: String,
    pub cnamgflgnpf: String,
    pub blpejecgljg: i64,
    pub omhmgmcicih: i64,
    #[serde(rename = "pushTipsId")]
    pub push_tips_id: Option<i64>,
    pub ojliecmjopd: Option<i64>,
}
