/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ExpeditionBonusExcelConfigData = Vec<ExpeditionBonusExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ExpeditionBonusExcelConfigDatum {
    pub id: i64,
    pub avatar_level: i64,
    pub probability: f64,
}
