// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ExpeditionBonusExcelConfigData = Vec<ExpeditionBonusExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ExpeditionBonusExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "avatarLevel")]
    pub avatar_level: i64,

    #[serde(rename = "probability")]
    pub probability: f64,
}

pub fn load() -> Result<ExpeditionBonusExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ExpeditionBonusExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
