/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FindHilichurlExcelConfigData = Vec<FindHilichurlExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct FindHilichurlExcelConfigDatum {
    pub id: i64,
    pub activity_id: i64,
    pub reward_preview_id: i64,
    pub guide_quest_id: i64,
    pub end_quest_id: i64,
    pub assignment_id_list: Vec<i64>,
    #[serde(rename = "HiliWeiIdList")]
    pub hili_wei_id_list: Vec<i64>,
}
