// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FireworksFactorExcelConfigData = Vec<FireworksFactorExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct FireworksFactorExcelConfigDatum {
    #[serde(rename = "NOFHGFFJAKA")]
    pub nofhgffjaka: String,

    #[serde(rename = "NBMPEOMOMFF")]
    pub nbmpeomomff: i64,

    #[serde(rename = "DEDABCPHCJG")]
    pub dedabcphcjg: String,

    #[serde(rename = "MLNEPIGMABN")]
    pub mlnepigmabn: i64,

    #[serde(rename = "MLINHFHMPOH")]
    pub mlinhfhmpoh: i64,

    #[serde(rename = "DPDGOGBAFHF")]
    pub dpdgogbafhf: i64,

    #[serde(rename = "DKELJPIPCBI")]
    pub dkeljpipcbi: f64,
}

pub fn load() -> Result<FireworksFactorExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "FireworksFactorExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
