// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FireworksLaunchExcelConfigData = Vec<FireworksLaunchExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct FireworksLaunchExcelConfigDatum {
    #[serde(rename = "CKDDMLJBHDH")]
    pub ckddmljbhdh: String,

    #[serde(rename = "defaultValue")]
    pub default_value: i64,

    #[serde(rename = "PPHOOOAAADO")]
    pub pphoooaaado: Vec<i64>,

    #[serde(rename = "IMHCBLIPLDP")]
    pub imhcblipldp: i64,

    #[serde(rename = "OKGPFLNDEPL")]
    pub okgpflndepl: i64,
}

pub fn load() -> Result<FireworksLaunchExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "FireworksLaunchExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
