// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FishBaitExcelConfigData = Vec<FishBaitExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct FishBaitExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "EGAPHJFAJBD")]
    pub egaphjfajbd: Vec<Egaphjfajbd>,

    #[serde(rename = "FGJDHHIOADH")]
    pub fgjdhhioadh: i64,

    #[serde(rename = "PGAMPCIOOBD")]
    pub pgampcioobd: Vec<i64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Egaphjfajbd {
    #[serde(rename = "AJPOGMPFNDO")]
    pub ajpogmpfndo: Option<i64>,

    #[serde(rename = "weight")]
    pub weight: Option<f64>,

    #[serde(rename = "ABAOCKKOHHF")]
    pub abaockkohhf: Option<f64>,
}

pub fn load() -> Result<FishBaitExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "FishBaitExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
