// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type FleurFairBuffEnergyStatExcelConfigData = Vec<FleurFairBuffEnergyStatExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct FleurFairBuffEnergyStatExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "galleryId")]
    pub gallery_id: i64,

    #[serde(rename = "statParam")]
    pub stat_param: String,

    #[serde(rename = "priority")]
    pub priority: i64,

    #[serde(rename = "titleTextMapHash")]
    pub title_text_map_hash: i64,
}

pub fn load() -> Result<FleurFairBuffEnergyStatExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "FleurFairBuffEnergyStatExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
