// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FungusPlotDungeonEnemyExcelConfigData = Vec<FungusPlotDungeonEnemyExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct FungusPlotDungeonEnemyExcelConfigDatum {
    #[serde(rename = "JLPIEBNDCEH")]
    pub jlpiebndceh: i64,

    #[serde(rename = "CBCCAFAHECC")]
    pub cbccafahecc: i64,

    #[serde(rename = "DNCIPLNHMJP")]
    pub dnciplnhmjp: i64,

    #[serde(rename = "CDCFOHKPCNL")]
    pub cdcfohkpcnl: String,

    #[serde(rename = "NBAKEHOAKJN")]
    pub nbakehoakjn: String,

    #[serde(rename = "NFEFALIJGPB")]
    pub nfefalijgpb: String,
}

pub fn load() -> Result<FungusPlotDungeonEnemyExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "FungusPlotDungeonEnemyExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
