/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FungusFighterV2ExcelConfigData = Vec<FungusFighterV2ExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct FungusFighterV2ExcelConfigDatum {
    #[serde(rename = "levelId")]
    pub level_id: i64,
    #[serde(rename = "dayIndex")]
    pub day_index: i64,
    #[serde(rename = "dungeonId")]
    pub dungeon_id: i64,
    #[serde(rename = "galleryId")]
    pub gallery_id: i64,
    pub nonlkdommko: Vec<i64>,
    pub ccbfkibkldk: Vec<i64>,
    pub fibpffonekn: Vec<i64>,
    #[serde(rename = "levelNameTextMapHash")]
    pub level_name_text_map_hash: i64,
    #[serde(rename = "levelDescTextMapHash")]
    pub level_desc_text_map_hash: i64,
    pub cbdbkhlfldo: i64,
    pub fnkkekjfmko: i64,
    pub logcfijkfcg: i64,
    pub nafkliakakh: String,
    #[serde(rename = "watcherList")]
    pub watcher_list: Vec<i64>,
    pub ngmnhbcnehd: i64,
    pub hjkbodemgam: Option<bool>,
    pub nibghhjeboh: Option<i64>,
    pub obolcfkdjlg: Option<bool>,
}
