// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FungusBaseExcelConfigData = Vec<FungusBaseExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct FungusBaseExcelConfigDatum {
    #[serde(rename = "activityId")]
    pub activity_id: i64,

    #[serde(rename = "FMNCFIBCFPC")]
    pub fmncfibcfpc: i64,

    #[serde(rename = "HIAFDAAGDBF")]
    pub hiafdaagdbf: i64,

    #[serde(rename = "EEOGJPPDLGG")]
    pub eeogjppdlgg: i64,

    #[serde(rename = "PEEDIDNKJGL")]
    pub peedidnkjgl: i64,

    #[serde(rename = "BABIMDOIOCB")]
    pub babimdoiocb: i64,

    #[serde(rename = "DNILMCFJOKH")]
    pub dnilmcfjokh: i64,

    #[serde(rename = "DCLLBOGKNFM")]
    pub dcllbogknfm: String,

    #[serde(rename = "DCIGMFKFEIC")]
    pub dcigmfkfeic: Vec<String>,

    #[serde(rename = "ELCKJPNOBJF")]
    pub elckjpnobjf: String,

    #[serde(rename = "ECELMLJHKHA")]
    pub ecelmljhkha: i64,

    #[serde(rename = "JPDPEAJNIOP")]
    pub jpdpeajniop: i64,

    #[serde(rename = "GIJHOHHNFHI")]
    pub gijhohhnfhi: Vec<i64>,

    #[serde(rename = "LJEPPINDHOP")]
    pub ljeppindhop: Vec<i64>,

    #[serde(rename = "IJDDABFAGPD")]
    pub ijddabfagpd: i64,

    #[serde(rename = "MKFAHADFLIF")]
    pub mkfahadflif: i64,

    #[serde(rename = "FJGJPCFNFDL")]
    pub fjgjpcfnfdl: i64,

    #[serde(rename = "GIJMFINLPAM")]
    pub gijmfinlpam: i64,

    #[serde(rename = "HJENILHBDMJ")]
    pub hjenilhbdmj: i64,

    #[serde(rename = "LIBEKEMLJBE")]
    pub libekemljbe: i64,

    #[serde(rename = "GBCFINGALNL")]
    pub gbcfingalnl: i64,

    #[serde(rename = "JDPJDHLHOLP")]
    pub jdpjdhlholp: i64,

    #[serde(rename = "AEBKGCOCLOH")]
    pub aebkgcocloh: i64,

    #[serde(rename = "CCMKMLOJDND")]
    pub ccmkmlojdnd: i64,

    #[serde(rename = "NBEDAFCJKLP")]
    pub nbedafcjklp: i64,

    #[serde(rename = "EMNOOCBJJEK")]
    pub emnoocbjjek: i64,

    #[serde(rename = "PEAEKPCCGFJ")]
    pub peaekpccgfj: i64,

    #[serde(rename = "JGKEPLGLILM")]
    pub jgkeplglilm: i64,
}

pub fn load() -> Result<FungusBaseExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "FungusBaseExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
