/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FungusFighterV2ExcelConfigData = Vec<FungusFighterV2ExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct FungusFighterV2ExcelConfigDatum {
    #[serde(rename = "levelId")]
    pub level_id: i64,
    #[serde(rename = "dayIndex")]
    pub day_index: i64,
    #[serde(rename = "dungeonId")]
    pub dungeon_id: i64,
    #[serde(rename = "galleryId")]
    pub gallery_id: i64,
    pub pbfolfdelkb: Vec<i64>,
    pub lgcnmldcipe: Vec<i64>,
    pub majcbdnidgn: Vec<i64>,
    #[serde(rename = "levelNameTextMapHash")]
    pub level_name_text_map_hash: i64,
    #[serde(rename = "levelDescTextMapHash")]
    pub level_desc_text_map_hash: i64,
    pub odefifheben: i64,
    pub mfbfcgdfgkm: i64,
    pub hpcmnleehgl: i64,
    pub jfkeeeahdjo: String,
    #[serde(rename = "watcherList")]
    pub watcher_list: Vec<i64>,
    pub jglldaaihgb: i64,
    pub gdmdfigbpka: Option<bool>,
    pub dfdhfoegded: Option<i64>,
    pub lmjjbkheejl: Option<bool>,
}
