/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type FungusNameExcelConfigData = Vec<FungusNameExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct FungusNameExcelConfigDatum {
    pub kjcpnndnldd: i64,
    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,
    pub eflegbclion: i64,
}
