// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GachaRestrictConfigData = Vec<GachaRestrictConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct GachaRestrictConfigDatum {
    #[serde(rename = "OFEOFPMKMCB")]
    pub ofeofpmkmcb: i64,

    #[serde(rename = "OKCLEKFJNIG")]
    pub okclekfjnig: i64,

    #[serde(rename = "ONNFBNHOHPP")]
    pub onnfbnhohpp: i64,

    #[serde(rename = "OBJEAJJPNOF")]
    pub objeajjpnof: i64,
}

pub fn load() -> Result<GachaRestrictConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "GachaRestrictConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
