/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GadgetInteractExcelConfigData = Vec<GadgetInteractExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct GadgetInteractExcelConfigDatum {
    pub interact_id: i64,
    pub action_type: Option<ActionType>,
    pub param1: Option<i64>,
    pub consume_item_id: Vec<ConsumeItemId>,
    pub cost_items: Vec<CostItem>,
    pub ui_desc_text_map_hash: i64,
    #[serde(rename = "OKMCFOBHBKI")]
    pub okmcfobhbki: Vec<Okmcfobhbki>,
    pub consume_item_num: Option<bool>,
    pub ui_title_text_map_hash: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum ActionType {
    #[serde(rename = "INTERACT_ACTION_CONSUME_REGIONAL_PLAY_VAR")]
    InteractActionConsumeRegionalPlayVar,
    #[serde(rename = "INTERACT_ACTION_SET_GADGET_CHAIN_BUFF")]
    InteractActionSetGadgetChainBuff,
    #[serde(rename = "INTERACT_ACTION_STATE")]
    InteractActionState,
    #[serde(rename = "INTERACT_ACTION_UNLOCK_SPECIAL_TRANSPORT_POINT")]
    InteractActionUnlockSpecialTransportPoint,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ConsumeItemId {
    pub action_type: Option<ActionType>,
    pub param: Vec<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct CostItem {
    pub id: Option<i64>,
    pub count: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Okmcfobhbki {
    pub param: Vec<String>,
    pub cond_type: Option<CondType>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum CondType {
    #[serde(rename = "INTERACT_COND_OFFERING_LEVEL")]
    InteractCondOfferingLevel,
    #[serde(rename = "INTERACT_COND_REGIONAL_PLAY_VAR_GREATER_THAN")]
    InteractCondRegionalPlayVarGreaterThan,
    #[serde(rename = "INTERACT_COND_WIDGET_ON")]
    InteractCondWidgetOn,
}
