/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgArenaValueExcelConfigData = Vec<GcgArenaValueExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct GcgArenaValueExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    pub fjgcknbgmec: i64,
    pub defbijpbjfi: i64,
    pub ainchecpakc: i64,
    pub gcagbdlflgn: i64,
    pub eoomkeiejnk: i64,
    #[serde(rename = "matchId")]
    pub match_id: i64,
    pub padkibihlnl: Vec<String>,
}
