// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgCharacterLevelExcelConfigData = Vec<GcgCharacterLevelExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct GcgCharacterLevelExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "npcId")]
    pub npc_id: i64,

    #[serde(rename = "avatarId")]
    pub avatar_id: i64,

    #[serde(rename = "KJHAANJFIGB")]
    pub kjhaanjfigb: Vec<Kjhaanjfigb>,

    #[serde(rename = "DDCEJFKKBEO")]
    pub ddcejfkkbeo: i64,

    #[serde(rename = "NHFGOPOOJKE")]
    pub nhfgopoojke: i64,

    #[serde(rename = "FGEKEAEDLCI")]
    pub fgekeaedlci: Option<bool>,

    #[serde(rename = "DGOJCOGKCIM")]
    pub dgojcogkcim: Option<i64>,

    #[serde(rename = "KINKMFIFEGO")]
    pub kinkmfifego: Option<i64>,

    #[serde(rename = "NDEEAIHNEHK")]
    pub ndeeaihnehk: Vec<Option<serde_json::Value>>,

    #[serde(rename = "BDELGIJDDDJ")]
    pub bdelgijdddj: i64,

    #[serde(rename = "HIDBCKGBBFM")]
    pub hidbckgbbfm: i64,

    #[serde(rename = "EGICOOKDEEC")]
    pub egicookdeec: i64,

    #[serde(rename = "LNKFICEBPPN")]
    pub lnkficebppn: i64,

    #[serde(rename = "JPOCFCHFPAN")]
    pub jpocfchfpan: i64,

    #[serde(rename = "preQuestId")]
    pub pre_quest_id: Option<i64>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Kjhaanjfigb {
    #[serde(rename = "HKGOEJBFNMM")]
    pub hkgoejbfnmm: i64,

    #[serde(rename = "PBOJONACIHL")]
    pub pbojonacihl: i64,
}

pub fn load() -> Result<GcgCharacterLevelExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "GCGCharacterLevelExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
