/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgElementExcelConfigData = Vec<GcgElementExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct GcgElementExcelConfigDatum {
    pub clnhpphelgo: i64,
    pub iemnlcfaefj: i64,
    #[serde(rename = "type")]
    pub gcg_element_excel_config_datum_type: Option<String>,
    pub oolpbkimcel: Option<i64>,
    pub plgccjnaleh: Option<i64>,
}
