// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgGameExcelConfigData = Vec<GcgGameExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct GcgGameExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "GIPCKIEBBDO")]
    pub gipckiebbdo: i64,

    #[serde(rename = "IFEAPLFJIKH")]
    pub ifeaplfjikh: i64,

    #[serde(rename = "ADKOIFEDKIM")]
    pub adkoifedkim: Option<i64>,

    #[serde(rename = "NMABJHKFCEG")]
    pub nmabjhkfceg: Option<i64>,

    #[serde(rename = "guideName")]
    pub guide_name: GuideName,

    #[serde(rename = "INCBEIKFJKO")]
    pub incbeikfjko: Option<Incbeikfjko>,

    #[serde(rename = "OEEFBOIJEJB")]
    pub oeefboijejb: Option<Oeefboijejb>,

    #[serde(rename = "FGFLBIFHPBB")]
    pub fgflbifhpbb: Option<bool>,

    #[serde(rename = "FEDIPCHJHNH")]
    pub fedipchjhnh: Option<i64>,

    #[serde(rename = "FHBFDECLGEC")]
    pub fhbfdeclgec: Option<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum GuideName {
    #[serde(rename = "")]
    Empty,

    #[serde(rename = "Tutorial_1_1")]
    Tutorial1_1,

    #[serde(rename = "Tutorial_1_2")]
    Tutorial1_2,

    #[serde(rename = "Tutorial_1_4")]
    Tutorial1_4,

    #[serde(rename = "Tutorial_1_5")]
    Tutorial1_5,

    #[serde(rename = "Tutorial_2_1")]
    Tutorial2_1,

    #[serde(rename = "Tutorial_2_2")]
    Tutorial2_2,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Incbeikfjko {
    #[serde(rename = "AI")]
    Ai,

    #[serde(rename = "PVE")]
    Pve,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Oeefboijejb {
    #[serde(rename = "SELF")]
    OeefboijejbSelf,
}

pub fn load() -> Result<GcgGameExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "GCGGameExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
