/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgSkillExcelConfigData = Vec<GcgSkillExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "PascalCase")]
pub struct GcgSkillExcelConfigDatum {
    pub id: i64,
    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,
    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,
    #[serde(rename = "HHHMJFBFAKD")]
    pub hhhmjfbfakd: String,
    #[serde(rename = "ECMKHGAKLKG")]
    pub ecmkhgaklkg: String,
    #[serde(rename = "FLMGNEKGPLG")]
    pub flmgnekgplg: String,
    #[serde(rename = "GCIHBPAOPAN")]
    pub gcihbpaopan: Vec<Gcihbpaopan>,
    #[serde(rename = "BHFFINOFADA")]
    pub bhffinofada: Vec<Bhffinofada>,
    #[serde(rename = "CJGDMKEFDHN")]
    pub cjgdmkefdhn: Option<Cjgdmkefdhn>,
    #[serde(rename = "EOPBDEHKBGD")]
    pub eopbdehkbgd: Vec<i64>,
    #[serde(rename = "LAFICGPFHOC")]
    pub laficgpfhoc: Vec<i64>,
    #[serde(rename = "DBDFFEOBDEP")]
    pub dbdffeobdep: Option<f64>,
    #[serde(rename = "DFJPBIKLOHJ")]
    pub dfjpbiklohj: Option<i64>,
    #[serde(rename = "LJHBINILLMN")]
    pub ljhbinillmn: Option<i64>,
    #[serde(rename = "JFKHBLDNCLG")]
    pub jfkhbldnclg: Option<f64>,
    #[serde(rename = "PLHNAAPMNEF")]
    pub plhnaapmnef: Option<bool>,
    #[serde(rename = "NCKAAIOMOMJ")]
    pub nckaaiomomj: Option<Nckaaiomomj>,
    #[serde(rename = "isHidden")]
    pub is_hidden: Option<bool>,
    #[serde(rename = "DOEENMDENPL")]
    pub doeenmdenpl: Option<bool>,
    #[serde(rename = "BCANDJAFMMK")]
    pub bcandjafmmk: Option<bool>,
    #[serde(rename = "GDADPLPEPGM")]
    pub gdadplpepgm: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Bhffinofada {
    #[serde(rename = "GCG_SKILL_TAG_A")]
    GcgSkillTagA,
    #[serde(rename = "GCG_SKILL_TAG_E")]
    GcgSkillTagE,
    #[serde(rename = "GCG_SKILL_TAG_NONE")]
    GcgSkillTagNone,
    #[serde(rename = "GCG_SKILL_TAG_PASSIVE")]
    GcgSkillTagPassive,
    #[serde(rename = "GCG_SKILL_TAG_Q")]
    GcgSkillTagQ,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Cjgdmkefdhn {
    #[serde(rename = "OnBannerShow")]
    OnBannerShow,
    #[serde(rename = "OnBehaviorStart")]
    OnBehaviorStart,
    #[serde(rename = "OnCostReviseReceived")]
    OnCostReviseReceived,
    #[serde(rename = "OnHitLanded")]
    OnHitLanded,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Gcihbpaopan {
    #[serde(rename = "NNPOIFOHFNM")]
    pub nnpoifohfnm: Option<Nnpoifohfnm>,
    pub count: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Nnpoifohfnm {
    #[serde(rename = "GCG_COST_DICE_ANEMO")]
    GcgCostDiceAnemo,
    #[serde(rename = "GCG_COST_DICE_CRYO")]
    GcgCostDiceCryo,
    #[serde(rename = "GCG_COST_DICE_DENDRO")]
    GcgCostDiceDendro,
    #[serde(rename = "GCG_COST_DICE_ELECTRO")]
    GcgCostDiceElectro,
    #[serde(rename = "GCG_COST_DICE_GEO")]
    GcgCostDiceGeo,
    #[serde(rename = "GCG_COST_DICE_HYDRO")]
    GcgCostDiceHydro,
    #[serde(rename = "GCG_COST_DICE_PYRO")]
    GcgCostDicePyro,
    #[serde(rename = "GCG_COST_DICE_SAME")]
    GcgCostDiceSame,
    #[serde(rename = "GCG_COST_DICE_VOID")]
    GcgCostDiceVoid,
    #[serde(rename = "GCG_COST_ENERGY")]
    GcgCostEnergy,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Nckaaiomomj {
    #[serde(rename = "Self")]
    NckaaiomomjSelf,
}
