/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgShopSubTabExcelConfigData = Vec<GcgShopSubTabExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct GcgShopSubTabExcelConfigDatum {
    pub pipnajghcbi: Vec<i64>,
    pub id: i64,
    #[serde(rename = "subTagNameTextMapHash")]
    pub sub_tag_name_text_map_hash: i64,
}
