/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgTalkDetailExcelConfigData = Vec<GcgTalkDetailExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct GcgTalkDetailExcelConfigDatum {
    pub alhinaeoeli: i64,
    pub eihfnomgjel: Vec<i64>,
    pub ngciojodoji: Vec<i64>,
    pub mbopailokli: Vec<i64>,
    pub gkpllaldfjd: Vec<Gkpllaldfjd>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Gkpllaldfjd {
    #[serde(rename = "GCG_TALK_EMOJI_AWKWARD")]
    GcgTalkEmojiAwkward,
    #[serde(rename = "GCG_TALK_EMOJI_ELATION")]
    GcgTalkEmojiElation,
    #[serde(rename = "GCG_TALK_EMOJI_HAPPY")]
    GcgTalkEmojiHappy,
    #[serde(rename = "GCG_TALK_EMOJI_MAD")]
    GcgTalkEmojiMad,
    #[serde(rename = "GCG_TALK_EMOJI_NON")]
    GcgTalkEmojiNon,
}
