// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgTalkExcelConfigData = Vec<GcgTalkExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct GcgTalkExcelConfigDatum {
    #[serde(rename = "IDNICJNHDFF")]
    pub idnicjnhdff: i64,

    #[serde(rename = "NFPBAOPFKOB")]
    pub nfpbaopfkob: i64,

    #[serde(rename = "ALKLNHOFBNG")]
    pub alklnhofbng: i64,

    #[serde(rename = "ADDKJHCPJBF")]
    pub addkjhcpjbf: Option<i64>,

    #[serde(rename = "CFAEHEMKMNF")]
    pub cfaehemkmnf: Option<i64>,

    #[serde(rename = "JJDHEDIELLH")]
    pub jjdhediellh: Option<i64>,

    #[serde(rename = "JMJFMNDOGLH")]
    pub jmjfmndoglh: Option<i64>,

    #[serde(rename = "LHMDLBIBIPE")]
    pub lhmdlbibipe: i64,

    #[serde(rename = "PIJOEHNBEJN")]
    pub pijoehnbejn: i64,

    #[serde(rename = "IACKPCPKOHO")]
    pub iackpcpkoho: Option<i64>,

    #[serde(rename = "KKHGLJOGDGO")]
    pub kkhgljogdgo: Option<i64>,

    #[serde(rename = "HBPEGCLACLM")]
    pub hbpegclaclm: Option<i64>,

    #[serde(rename = "GIHOFCHGGBM")]
    pub gihofchggbm: Option<i64>,

    #[serde(rename = "FIAGDEGBNEB")]
    pub fiagdegbneb: Option<i64>,

    #[serde(rename = "NLCAELBPNFC")]
    pub nlcaelbpnfc: Option<i64>,

    #[serde(rename = "DLOIFGPEJEP")]
    pub dloifgpejep: Option<i64>,

    #[serde(rename = "JGILBOBNCHL")]
    pub jgilbobnchl: Option<i64>,
}

pub fn load() -> Result<GcgTalkExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "GCGTalkExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
