// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GcgTalkDetailIconExcelConfigData = Vec<GcgTalkDetailIconExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct GcgTalkDetailIconExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "iconName")]
    pub icon_name: String,

    #[serde(rename = "type")]
    pub gcg_talk_detail_icon_excel_config_datum_type: Option<Type>,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Type {
    #[serde(rename = "Monster")]
    Monster,

    #[serde(rename = "NPC")]
    Npc,
}

pub fn load() -> Result<GcgTalkDetailIconExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "GCGTalkDetailIconExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
