// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type GravenInnocenceCarveOverallExcelConfigData = Vec<GravenInnocenceCarveOverallExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct GravenInnocenceCarveOverallExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "groupIdList")]
    pub group_id_list: Vec<i64>,

    #[serde(rename = "NCFINPOEJCK")]
    pub ncfinpoejck: Vec<i64>,

    #[serde(rename = "GFGGIBHBMLK")]
    pub gfggibhbmlk: Vec<i64>,

    #[serde(rename = "BHNMKCGFFMC")]
    pub bhnmkcgffmc: i64,
}

pub fn load() -> Result<GravenInnocenceCarveOverallExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "GravenInnocenceCarveOverallExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
