// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type GroupTagExcelConfigData = Vec<GroupTagExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct GroupTagExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "HCIGDMCFGOP")]
    pub hcigdmcfgop: String,
}

pub fn load() -> Result<GroupTagExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "GroupTagExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
