// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type GuideTriggerExcelConfigData = Vec<GuideTriggerExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct GuideTriggerExcelConfigDatum {
    #[serde(rename = "guideName")]
    pub guide_name: String,

    #[serde(rename = "type")]
    pub guide_trigger_excel_config_datum_type: String,

    #[serde(rename = "openState")]
    pub open_state: Option<String>,

    #[serde(rename = "param1")]
    pub param1: Option<i64>,
}

pub fn load() -> Result<GuideTriggerExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "GuideTriggerExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
