/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type HandbookMainQuestGuideExcelConfigData = Vec<HandbookMainQuestGuideExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct HandbookMainQuestGuideExcelConfigDatum {
    pub ehohaokeddj: i64,
    pub kmhmppdllcj: i64,
    pub fabgglpjbgi: Vec<i64>,
}
