/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type HideAndSeekSkillExcelConfigData = Vec<HideAndSeekSkillExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HideAndSeekSkillExcelConfigDatum {
    pub id: i64,
    #[serde(rename = "skillID")]
    pub skill_id: i64,
    pub order: i64,
    pub skill_category: SkillCategory,
    pub skill_sub_category: SkillSubCategory,
    pub is_default: Option<bool>,
    pub category_desc_text_map_hash: i64,
    pub skill_icon_path_hash: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SkillCategory {
    #[serde(rename = "HIDE_AND_SEEK_SKILL_CATEGORY_GHOST")]
    HideAndSeekSkillCategoryGhost,
    #[serde(rename = "HIDE_AND_SEEK_SKILL_CATEGORY_HUNTER")]
    HideAndSeekSkillCategoryHunter,
    #[serde(rename = "HIDE_AND_SEEK_SKILL_CATEGORY_PREY")]
    HideAndSeekSkillCategoryPrey,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum SkillSubCategory {
    #[serde(rename = "HIDE_AND_SEEK_SKILL_SUB_CATEGORY_COMMON")]
    HideAndSeekSkillSubCategoryCommon,
    #[serde(rename = "HIDE_AND_SEEK_SKILL_SUB_CATEGORY_SKILL1")]
    HideAndSeekSkillSubCategorySkill1,
    #[serde(rename = "HIDE_AND_SEEK_SKILL_SUB_CATEGORY_SKILL2")]
    HideAndSeekSkillSubCategorySkill2,
}
