/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type HomeworldLevelExcelConfigData = Vec<HomeworldLevelExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HomeworldLevelExcelConfigDatum {
    pub level: i64,
    pub exp: Option<i64>,
    pub comfort_point_limit: i64,
    pub home_coin_store_limit: i64,
    pub home_fetter_exp_store_limit: i64,
    pub reward_id: i64,
    pub furniture_make_slot_count: i64,
    pub outdoor_unlock_block_count: i64,
    pub free_unlock_module_count: i64,
    pub deploy_npc_count: i64,
    pub djinn_gadget_id: i64,
    pub limit_shop_goods_count: i64,
    pub level_funcs: Vec<String>,
}
