/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type HuntingClueMonsterExcelConfigData = Vec<HuntingClueMonsterExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct HuntingClueMonsterExcelConfigDatum {
    pub config_id: i64,
    pub monster_id: i64,
    pub revise_level_id: i64,
    pub group_type: GroupType,
    pub monster_group_id: i64,
    pub level: i64,
    pub is_clue_monster: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum GroupType {
    #[serde(rename = "HUNTING_GROUP_TYPE_CLUE")]
    HuntingGroupTypeClue,
}
