// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type IconAdsorbEffectExcelConfigData = Vec<IconAdsorbEffectExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct IconAdsorbEffectExcelConfigDatum {
    #[serde(rename = "effectId")]
    pub effect_id: i64,

    #[serde(rename = "iconIdList")]
    pub icon_id_list: Vec<i64>,
}

pub fn load() -> Result<IconAdsorbEffectExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "IconAdsorbEffectExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
