// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ImageWorldExcelConfigData = Vec<ImageWorldExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ImageWorldExcelConfigDatum {
    #[serde(rename = "ID")]
    pub id: i64,

    #[serde(rename = "FIAEINCAFDD")]
    pub fiaeincafdd: Option<bool>,

    #[serde(rename = "GNPANBLGFLA")]
    pub gnpanblgfla: Option<bool>,

    #[serde(rename = "NEABDPLCIIP")]
    pub neabdplciip: bool,

    #[serde(rename = "LLBNGGGPHHK")]
    pub llbngggphhk: bool,
}

pub fn load() -> Result<ImageWorldExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ImageWorldExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
