/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type InferenceConclusionExcelConfigData = Vec<InferenceConclusionExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InferenceConclusionExcelConfigDatum {
    pub conclusion_id: i64,
    pub word_list: Vec<i64>,
    pub submit_error_dialog_id: i64,
    pub submit_success_talk_id: Option<i64>,
}
