/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type InstableSprayOverallExcelConfigData = Vec<InstableSprayOverallExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InstableSprayOverallExcelConfigDatum {
    pub activity_id: i64,
    pub schedule_id: i64,
    pub score_ranks: Vec<i64>,
    pub dungeon_entry_id: i64,
    #[serde(rename = "KNLBEIJPLKL")]
    pub knlbeijplkl: i64,
    #[serde(rename = "HCPHOJPIILM")]
    pub hcphojpiilm: i64,
}
