/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type InvestigationConfigData = Vec<InvestigationConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct InvestigationConfigDatum {
    pub id: i64,
    pub city_id: i64,
    pub next_investigation_id_list: Vec<i64>,
    pub unlock_open_state_type: Option<String>,
    pub reward_id: Option<i64>,
    pub title_text_map_hash: i64,
    pub investigation_type: Option<String>,
    pub unlock_level: Option<i64>,
    #[serde(rename = "IPLOJIFBNNM")]
    pub iplojifbnnm: Option<bool>,
}
