/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type IrodoriMasterLevelExcelConfigData = Vec<IrodoriMasterLevelExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct IrodoriMasterLevelExcelConfigDatum {
    #[serde(rename = "Id")]
    pub id: i64,
    pub scene_id: i64,
    pub group_id: i64,
    pub point_id: i64,
    pub gallery_id: i64,
    pub cutscene: String,
    pub trial_avatar_list: Vec<i64>,
    pub watcher_list: Vec<i64>,
}
