/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type LampProgressControlConfigData = Vec<LampProgressControlConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LampProgressControlConfigDatum {
    pub hour: i64,
    pub min_progress: i64,
    pub max_progress: i64,
}
