/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type LandSoundExcelConfigData = Vec<LandSoundExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LandSoundExcelConfigDatum {
    pub name: String,
    pub audio_name: String,
    pub id: Option<i64>,
}
