/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type LanV2ProjectionExcelConfigData = Vec<LanV2ProjectionExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LanV2ProjectionExcelConfigDatum {
    pub schedule_id: i64,
    pub sensitivity_free_rotation: i64,
    pub sensitivity_single_axis_rotation: i64,
    pub sensitivity_single_axis_translation: i64,
    pub sensitivity_free_rotation_joypad: i64,
    pub sensitivity_single_axis_rotation_joypad: i64,
    pub sensitivity_single_axis_translation_joypad: f64,
    pub push_tips_id_joypad: i64,
    pub push_tips_id_touch: i64,
    pub push_tips_id_mouse: i64,
    pub time_threshold_unlock_answer: i64,
    pub time_threshold_show_standby_prompt: i64,
    pub time_threshold_show_continuous_progress: i64,
    pub lead_guides: Vec<String>,
    pub guides: Vec<String>,
    pub guide_quest_id: i64,
    pub name_text_map_hash: i64,
    pub desc_text_map_hash: i64,
}
