// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type LanV3AvatarSelectExcelConfigData = Vec<LanV3AvatarSelectExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LanV3AvatarSelectExcelConfigDatum {
    #[serde(rename = "avatarId")]
    pub avatar_id: i64,

    #[serde(rename = "BAFFKIDEOOP")]
    pub baffkideoop: i64,
}

pub fn load() -> Result<LanV3AvatarSelectExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "LanV3AvatarSelectExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
