// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type LanV3BoatExcelConfigData = Vec<LanV3BoatExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LanV3BoatExcelConfigDatum {
    #[serde(rename = "LNLDCBMGPBG")]
    pub lnldcbmgpbg: i64,

    #[serde(rename = "type")]
    pub lan_v3_boat_excel_config_datum_type: String,

    #[serde(rename = "galleryId")]
    pub gallery_id: i64,

    #[serde(rename = "controlGroupId")]
    pub control_group_id: i64,

    #[serde(rename = "prepareTime")]
    pub prepare_time: i64,

    #[serde(rename = "EKMCEBKFAPE")]
    pub ekmcebkfape: i64,

    #[serde(rename = "DLPOGMLFAFE")]
    pub dlpogmlfafe: i64,

    #[serde(rename = "IFCEOFJPGIL")]
    pub ifceofjpgil: i64,

    #[serde(rename = "CPKJMBHIHOG")]
    pub cpkjmbhihog: i64,

    #[serde(rename = "BINBBBBJGKJ")]
    pub binbbbbjgkj: i64,

    #[serde(rename = "limitRegion")]
    pub limit_region: String,

    #[serde(rename = "MKFJDLBLCHI")]
    pub mkfjdlblchi: Vec<i64>,

    #[serde(rename = "DHENFKBIHPG")]
    pub dhenfkbihpg: Vec<i64>,

    #[serde(rename = "HDDIELMIHBN")]
    pub hddielmihbn: Vec<i64>,

    #[serde(rename = "NJBMBIIEODE")]
    pub njbmbiieode: Option<f64>,
}

pub fn load() -> Result<LanV3BoatExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "LanV3BoatExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
