// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type LanV2ProjectionExcelConfigData = Vec<LanV2ProjectionExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LanV2ProjectionExcelConfigDatum {
    #[serde(rename = "scheduleId")]
    pub schedule_id: i64,

    #[serde(rename = "DAMDLCKKBLF")]
    pub damdlckkblf: f64,

    #[serde(rename = "LLMBBIFGFDO")]
    pub llmbbifgfdo: f64,

    #[serde(rename = "NOCENHKADGI")]
    pub nocenhkadgi: f64,

    #[serde(rename = "NHDHBOHNLBD")]
    pub nhdhbohnlbd: f64,

    #[serde(rename = "PKNHBIIAEOF")]
    pub pknhbiiaeof: f64,

    #[serde(rename = "CBBGMDAMDFE")]
    pub cbbgmdamdfe: f64,

    #[serde(rename = "LOLKJICDOHJ")]
    pub lolkjicdohj: i64,

    #[serde(rename = "KIECAFNGNEN")]
    pub kiecafngnen: i64,

    #[serde(rename = "MOODCIIMBPF")]
    pub moodciimbpf: i64,

    #[serde(rename = "HLFDHNFADJG")]
    pub hlfdhnfadjg: i64,

    #[serde(rename = "ANMANBLFIAO")]
    pub anmanblfiao: i64,

    #[serde(rename = "FFKDJFDNMLL")]
    pub ffkdjfdnmll: i64,

    #[serde(rename = "NBHBGMOJOOH")]
    pub nbhbgmojooh: Vec<String>,

    #[serde(rename = "CHKACKKBFBA")]
    pub chkackkbfba: Vec<String>,

    #[serde(rename = "guideQuestId")]
    pub guide_quest_id: i64,

    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,
}

pub fn load() -> Result<LanV2ProjectionExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "LanV2ProjectionExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
