// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type LanV3CampLevelExcelConfigData = Vec<LanV3CampLevelExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LanV3CampLevelExcelConfigDatum {
    #[serde(rename = "levelId")]
    pub level_id: i64,

    #[serde(rename = "IAEDJIKKJDH")]
    pub iaedjikkjdh: i64,

    #[serde(rename = "KKAAOAGIFEF")]
    pub kkaaoagifef: i64,

    #[serde(rename = "AJFJEMAOJHJ")]
    pub ajfjemaojhj: String,
}

pub fn load() -> Result<LanV3CampLevelExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "LanV3CampLevelExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
