/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type LanV3ShadowStageExcelConfigData = Vec<LanV3ShadowStageExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct LanV3ShadowStageExcelConfigDatum {
    pub stage_id: i64,
    pub stage_name_text_map_hash: i64,
    #[serde(rename = "INAJKAJJBHG")]
    pub inajkajjbhg: Vec<i64>,
}
