// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type LanV2FireworksSkillDataExcelConfigData = Vec<LanV2FireworksSkillDataExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LanV2FireworksSkillDataExcelConfigDatum {
    #[serde(rename = "ONEJALHEENC")]
    pub onejalheenc: i64,

    #[serde(rename = "ABPEKGBELEK")]
    pub abpekgbelek: String,

    #[serde(rename = "HGDAOFFBMNN")]
    pub hgdaoffbmnn: i64,

    #[serde(rename = "HEFLHCEDHNO")]
    pub heflhcedhno: i64,

    #[serde(rename = "PHKDMPEDEBF")]
    pub phkdmpedebf: Option<i64>,

    #[serde(rename = "EEKMEFDLGLI")]
    pub eekmefdlgli: Option<i64>,

    #[serde(rename = "NEKFJLLMHAI")]
    pub nekfjllmhai: Option<i64>,

    #[serde(rename = "HBILLDFLLHK")]
    pub hbilldfllhk: Vec<i64>,

    #[serde(rename = "HCNIILDMFNM")]
    pub hcniildmfnm: i64,

    #[serde(rename = "IFLGLLEHDNL")]
    pub iflgllehdnl: i64,

    #[serde(rename = "FOCHHNMHONL")]
    pub fochhnmhonl: Vec<i64>,

    #[serde(rename = "LILAPKAGEGP")]
    pub lilapkagegp: Option<i64>,
}

pub fn load() -> Result<LanV2FireworksSkillDataExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "LanV2FireworksSkillDataExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
