// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type LanV2ProjectionExcelConfigData = Vec<LanV2ProjectionExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LanV2ProjectionExcelConfigDatum {
    #[serde(rename = "scheduleId")]
    pub schedule_id: i64,

    #[serde(rename = "EGFFDLIKCMI")]
    pub egffdlikcmi: f64,

    #[serde(rename = "JFLDBCFPIDH")]
    pub jfldbcfpidh: f64,

    #[serde(rename = "EABFLGDNPHF")]
    pub eabflgdnphf: f64,

    #[serde(rename = "PAMFKJKOOJD")]
    pub pamfkjkoojd: f64,

    #[serde(rename = "MNAGKLHIDBH")]
    pub mnagklhidbh: f64,

    #[serde(rename = "HJHGLHFEAGB")]
    pub hjhglhfeagb: f64,

    #[serde(rename = "DCABJOHOIEG")]
    pub dcabjohoieg: i64,

    #[serde(rename = "NHJCFDABFEA")]
    pub nhjcfdabfea: i64,

    #[serde(rename = "MJEHLBOGCLH")]
    pub mjehlbogclh: i64,

    #[serde(rename = "DNGPOAODBJP")]
    pub dngpoaodbjp: i64,

    #[serde(rename = "OKMNLABMLFB")]
    pub okmnlabmlfb: i64,

    #[serde(rename = "PHJKDDOBHFB")]
    pub phjkddobhfb: i64,

    #[serde(rename = "MILNMCCMKBA")]
    pub milnmccmkba: Vec<String>,

    #[serde(rename = "FEDNNAGAPGN")]
    pub fednnagapgn: Vec<String>,

    #[serde(rename = "guideQuestId")]
    pub guide_quest_id: i64,

    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,
}

pub fn load() -> Result<LanV2ProjectionExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "LanV2ProjectionExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
