/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type LevelTagExcelConfigData = Vec<LevelTagExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct LevelTagExcelConfigDatum {
    pub id: i64,
    pub dlgniidbhnp: String,
    #[serde(rename = "sceneId")]
    pub scene_id: i64,
    pub jhegeckomip: Vec<i64>,
    pub bjdilblkkhi: Vec<i64>,
    pub belbjlfflbb: Option<bool>,
    pub dceilaloada: Option<i64>,
    pub ggnaphlcbje: Vec<i64>,
}
