// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type LuminanceStoneChallengeOverallExcelConfigData = Vec<LuminanceStoneChallengeOverallExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct LuminanceStoneChallengeOverallExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "activityId")]
    pub activity_id: i64,

    #[serde(rename = "KOPDLIEFHCM")]
    pub kopdliefhcm: i64,

    #[serde(rename = "NAOKDOKNBMH")]
    pub naokdoknbmh: i64,

    #[serde(rename = "FJCGEFNKMJP")]
    pub fjcgefnkmjp: Vec<i64>,

    #[serde(rename = "rewardPreviewId")]
    pub reward_preview_id: i64,

    #[serde(rename = "DMFBOHLKFHM")]
    pub dmfbohlkfhm: i64,
}

pub fn load() -> Result<LuminanceStoneChallengeOverallExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "LuminanceStoneChallengeOverallExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
