/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type LuminanceStoneChallengeOverallExcelConfigData = Vec<LuminanceStoneChallengeOverallExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct LuminanceStoneChallengeOverallExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "activityId")]
    pub activity_id: i64,
    pub phehdancdme: i64,
    pub aefdlpogmjc: i64,
    pub gkjankigjek: Vec<i64>,
    #[serde(rename = "rewardPreviewId")]
    pub reward_preview_id: i64,
    pub bnelfjlcbcj: i64,
}
