// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type ManualTextMapConfigData = Vec<ManualTextMapConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ManualTextMapConfigDatum {
    #[serde(rename = "textMapId")]
    pub text_map_id: String,

    #[serde(rename = "textMapContentTextMapHash")]
    pub text_map_content_text_map_hash: i64,

    #[serde(rename = "paramTypes")]
    pub param_types: Vec<ParamType>,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum ParamType {
    #[serde(rename = "TEXT_PARAM_AVATAR_NAME")]
    TextParamAvatarName,

    #[serde(rename = "TEXT_PARAM_NONE")]
    TextParamNone,

    #[serde(rename = "TEXT_PARAM_ROUTINE_TYPE")]
    TextParamRoutineType,
}

pub fn load() -> Result<ManualTextMapConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ManualTextMapConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
