/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type MaterialCodexExcelConfigData = Vec<MaterialCodexExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MaterialCodexExcelConfigDatum {
    #[serde(rename = "Id")]
    pub id: i64,
    pub material_id: i64,
    #[serde(rename = "SortOrder")]
    pub sort_order: i64,
    pub name_text_map_hash: i64,
    pub desc_text_map_hash: i64,
    pub icon: String,
    #[serde(rename = "DNPOBNNBADK")]
    pub dnpobnnbadk: i64,
    #[serde(rename = "KJALEOLMGOL")]
    pub kjaleolmgol: i64,
    #[serde(rename = "IHDKFJECCJO")]
    pub ihdkfjeccjo: i64,
    #[serde(rename = "GBHPOMMJONO")]
    pub gbhpommjono: i64,
    #[serde(rename = "AHJBLMDGJND")]
    pub ahjblmdgjnd: Option<i64>,
    pub is_disuse: Option<bool>,
    pub show_only_unlocked: Option<bool>,
    #[serde(rename = "type")]
    pub material_codex_excel_config_datum_type: Option<Type>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Type {
    #[serde(rename = "CODEX_COOKING_FOOD")]
    CodexCookingFood,
    #[serde(rename = "CODEX_WAR_TROPHIES")]
    CodexWarTrophies,
    #[serde(rename = "CODEX_WIDGET")]
    CodexWidget,
}
