/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type MaterialSourceDataExcelConfigData = Vec<MaterialSourceDataExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MaterialSourceDataExcelConfigDatum {
    pub id: i64,
    pub dungeon_list: Vec<i64>,
    pub jump_list: Vec<JumpList>,
    pub dungeon_group: Vec<i64>,
    pub jump_targets: Vec<JumpTarget>,
    pub jump_params: Vec<i64>,
    pub jump_descs: Vec<i64>,
    pub text_list: Vec<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct JumpList {
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum JumpTarget {
    #[serde(rename = "JUMP_INVESTIGATION")]
    JumpInvestigation,
    #[serde(rename = "JUMP_MALL")]
    JumpMall,
    #[serde(rename = "JUMP_MAP_OR_INVESTIGATION_TO_DUNGEON_ENTRY")]
    JumpMapOrInvestigationToDungeonEntry,
}
