/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type MichiaeErosionAreaExcelConfigData = Vec<MichiaeErosionAreaExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct MichiaeErosionAreaExcelConfigDatum {
    #[serde(rename = "areaId")]
    pub area_id: Option<i64>,
    pub a1: Option<i64>,
    pub a2: Option<f64>,
    pub a3: Option<f64>,
}
