// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type MichiaeOverallExcelConfigData = Vec<MichiaeOverallExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct MichiaeOverallExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "activityId")]
    pub activity_id: i64,

    #[serde(rename = "offeringId")]
    pub offering_id: i64,

    #[serde(rename = "MOMGOJANGJI")]
    pub momgojangji: i64,

    #[serde(rename = "GKPHBINIFNJ")]
    pub gkphbinifnj: i64,

    #[serde(rename = "KMFHPPAJMID")]
    pub kmfhppajmid: Vec<i64>,

    #[serde(rename = "GBLDBDHBBOJ")]
    pub gbldbdhbboj: i64,

    #[serde(rename = "DANEEOPOBEH")]
    pub daneeopobeh: f64,

    #[serde(rename = "MKCMOHONHBC")]
    pub mkcmohonhbc: f64,

    #[serde(rename = "LOLPBANFIEJ")]
    pub lolpbanfiej: i64,

    #[serde(rename = "CJBOMLCIMMB")]
    pub cjbomlcimmb: f64,

    #[serde(rename = "CMGECEDGGDL")]
    pub cmgecedggdl: i64,

    #[serde(rename = "EGHAOBDNKEH")]
    pub eghaobdnkeh: i64,

    #[serde(rename = "BDKMOLLEDJK")]
    pub bdkmolledjk: i64,
}

pub fn load() -> Result<MichiaeOverallExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "MichiaeOverallExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
