// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type MiracleRingDropExcelConfigData = Vec<MiracleRingDropExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct MiracleRingDropExcelConfigDatum {
    #[serde(rename = "miracleTag")]
    pub miracle_tag: String,

    #[serde(rename = "dropId")]
    pub drop_id: Vec<i64>,
}

pub fn load() -> Result<MiracleRingDropExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "MiracleRingDropExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
