// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type MonsterTitleExcelConfigData = Vec<MonsterTitleExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct MonsterTitleExcelConfigDatum {
    #[serde(rename = "titleID")]
    pub title_id: i64,

    #[serde(rename = "titleNameTextMapHash")]
    pub title_name_text_map_hash: i64,

    #[serde(rename = "isInverted")]
    pub is_inverted: Option<bool>,
}

pub fn load() -> Result<MonsterTitleExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "MonsterTitleExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
