/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type MonsterRelationshipExcelConfigData = Vec<MonsterRelationshipExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct MonsterRelationshipExcelConfigDatum {
    pub id: i64,
    pub tag_str: String,
    pub monster_rarity: MonsterRarity,
    #[serde(rename = "AIFFJKKGJMP")]
    pub aiffjkkgjmp: String,
    #[serde(rename = "LOLEANKNHEC")]
    pub loleanknhec: Option<bool>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum MonsterRarity {
    #[serde(rename = "MONSTER_RARITY_BIG_BOSS_MONSTER")]
    MonsterRarityBigBossMonster,
    #[serde(rename = "MONSTER_RARITY_BOSS_MONSTER")]
    MonsterRarityBossMonster,
    #[serde(rename = "MONSTER_RARITY_ELITE_MONSTER")]
    MonsterRarityEliteMonster,
    #[serde(rename = "MONSTER_RARITY_SMALL_ENV_ANIMAL")]
    MonsterRaritySmallEnvAnimal,
    #[serde(rename = "MONSTER_RARITY_SMALL_MONSTER")]
    MonsterRaritySmallMonster,
}
