// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type MonsterRelOverloadExcelConfigData = Vec<MonsterRelOverloadExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct MonsterRelOverloadExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "HAPPJDPDMCP")]
    pub happjdpdmcp: Happjdpdmcp,

    #[serde(rename = "BCFFALFNMNE")]
    pub bcffalfnmne: Bcffalfnmne,

    #[serde(rename = "BPNMHIJGEFJ")]
    pub bpnmhijgefj: Vec<Bpnmhijgefj>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Bpnmhijgefj {
    #[serde(rename = "paramList")]
    pub param_list: Vec<i64>,

    #[serde(rename = "KKKFFHGMABN")]
    pub kkkffhgmabn: Kkkffhgmabn,

    #[serde(rename = "monsterRarity")]
    pub monster_rarity: MonsterRarity,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Bcffalfnmne {
    #[serde(rename = "_MONSTER_FUNGUSSTATE_")]
    MonsterFungusstate,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Kkkffhgmabn {
    #[serde(rename = "蕈兽")]
    Empty,

    #[serde(rename = "大异化蕈兽")]
    Fluffy,

    #[serde(rename = "异化蕈兽")]
    Kkkffhgmabn,

    #[serde(rename = "大蕈兽")]
    Purple,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum MonsterRarity {
    #[serde(rename = "MONSTER_RARITY_ELITE_MONSTER")]
    MonsterRarityEliteMonster,

    #[serde(rename = "MONSTER_RARITY_SMALL_MONSTER")]
    MonsterRaritySmallMonster,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum Happjdpdmcp {
    #[serde(rename = "MONSTER_POLY_DROP_GV")]
    MonsterPolyDropGv,
}

pub fn load() -> Result<MonsterRelOverloadExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "MonsterRelOverloadExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
