// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type MusicGameDrumConfigData = Vec<MusicGameDrumConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct MusicGameDrumConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "KGONDJACLJA")]
    pub kgondjaclja: Vec<f64>,

    #[serde(rename = "BFPKCPNNMCA")]
    pub bfpkcpnnmca: Vec<f64>,

    #[serde(rename = "DFGDBLOCAJC")]
    pub dfgdblocajc: Vec<f64>,

    #[serde(rename = "EHLEFGMCFHE")]
    pub ehlefgmcfhe: Vec<f64>,

    #[serde(rename = "HBLCCLDEICF")]
    pub hblccldeicf: Vec<f64>,

    #[serde(rename = "FDOHIJDLEON")]
    pub fdohijdleon: i64,

    #[serde(rename = "FNKDHBOABHD")]
    pub fnkdhboabhd: i64,

    #[serde(rename = "JLFCAFCDGAF")]
    pub jlfcafcdgaf: i64,

    #[serde(rename = "NLIKBGGJLDO")]
    pub nlikbggjldo: i64,

    #[serde(rename = "PBBFEKLEOGJ")]
    pub pbbfekleogj: i64,

    #[serde(rename = "DIKNFKLBNPP")]
    pub diknfklbnpp: i64,

    #[serde(rename = "BGFHMBNKCLP")]
    pub bgfhmbnkclp: i64,

    #[serde(rename = "BPCBLICIIJO")]
    pub bpcbliciijo: Vec<f64>,

    #[serde(rename = "KAKNPCFEOFH")]
    pub kaknpcfeofh: f64,

    #[serde(rename = "DDIGMBFCPLA")]
    pub ddigmbfcpla: Vec<f64>,

    #[serde(rename = "DMFHGNJDKHB")]
    pub dmfhgnjdkhb: i64,

    #[serde(rename = "OENABOBOJEB")]
    pub oenabobojeb: f64,

    #[serde(rename = "GJFGDNGBPEE")]
    pub gjfgdngbpee: f64,

    #[serde(rename = "CEPDBHFKKHK")]
    pub cepdbhfkkhk: i64,

    #[serde(rename = "MPLPINDEEMH")]
    pub mplpindeemh: Vec<f64>,

    #[serde(rename = "IEJOPLFPGJL")]
    pub iejoplfpgjl: Vec<f64>,

    #[serde(rename = "LCMOIEFFHOD")]
    pub lcmoieffhod: Vec<f64>,

    #[serde(rename = "MLBNFLLMJPE")]
    pub mlbnfllmjpe: Vec<f64>,

    #[serde(rename = "OFCPIJDHNDJ")]
    pub ofcpijdhndj: i64,

    #[serde(rename = "DCOJAPHEMNK")]
    pub dcojaphemnk: Vec<i64>,

    #[serde(rename = "GHFLPIJLDOP")]
    pub ghflpijldop: Vec<i64>,

    #[serde(rename = "EBJHLILKEBE")]
    pub ebjhlilkebe: Vec<i64>,

    #[serde(rename = "HCHPGGBFOFO")]
    pub hchpggbfofo: Vec<f64>,

    #[serde(rename = "JKDMCCHIAGA")]
    pub jkdmcchiaga: Vec<f64>,

    #[serde(rename = "JMDPGBEIJOF")]
    pub jmdpgbeijof: Vec<i64>,
}

pub fn load() -> Result<MusicGameDrumConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "MusicGameDrumConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
