/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type OfferingOpenStateConfigData = Vec<OfferingOpenStateConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct OfferingOpenStateConfigDatum {
    pub offering_id: i64,
    pub open_state: String,
    pub item_limit: String,
    pub max_level_limit_type: String,
    pub is_continuous_level_up: Option<bool>,
    pub is_allow_host_in_mp_mode: Option<bool>,
    pub activity_id: Option<i64>,
    #[serde(rename = "DCDBNIINDOI")]
    pub dcdbniindoi: Option<i64>,
    #[serde(rename = "scenePointID")]
    pub scene_point_id: Option<i64>,
}
