// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type OfferingVersionExcelConfigData = Vec<OfferingVersionExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct OfferingVersionExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "offeringId")]
    pub offering_id: i64,

    #[serde(rename = "MGGEIGMNNFF")]
    pub mggeigmnnff: i64,
}

pub fn load() -> Result<OfferingVersionExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "OfferingVersionExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
