/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type OraionokamiDataExcelConfigData = Vec<OraionokamiDataExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct OraionokamiDataExcelConfigDatum {
    #[serde(rename = "configId")]
    pub config_id: i64,
    pub gcofdnmjlhg: i64,
    pub iljikhhkjij: i64,
    #[serde(rename = "serverBuffId")]
    pub server_buff_id: i64,
    pub flekpbfgbpc: Vec<i64>,
    pub jonkjnmkkhc: i64,
    pub dhaiejlmkeb: i64,
    pub mhehonlgehp: i64,
    #[serde(rename = "groupId")]
    pub group_id: i64,
    pub fmlcojfndgn: i64,
    #[serde(rename = "iconPath")]
    pub icon_path: String,
}
