/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type PerceptionTemplateExcelConfigData = Vec<PerceptionTemplateExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct PerceptionTemplateExcelConfigDatum {
    pub id: i64,
    pub hear_other_range_factor: i64,
    pub feel_range_factor: Option<f64>,
    pub hear_footstep_range_factor: Option<f64>,
}
