/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ProductPlayDetailConfigData = Vec<ProductPlayDetailConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ProductPlayDetailConfigDatum {
    pub play_type: String,
    pub item_name_text_map_hash: i64,
    pub config_id: i64,
    pub price_tier: String,
}
