// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type Ps4GroupExcelConfigData = Vec<Ps4GroupExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct Ps4GroupExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,

    #[serde(rename = "iconPath")]
    pub icon_path: String,
}

pub fn load() -> Result<Ps4GroupExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "PS4GroupExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
