// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type QteStepExcelConfigData = Vec<QteStepExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct QteStepExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "KCMGMGKOFAH")]
    pub kcmgmgkofah: String,

    #[serde(rename = "OMADNMNJELA")]
    pub omadnmnjela: Option<i64>,
}

pub fn load() -> Result<QteStepExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "QTEStepExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
