// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type QuestDialogDecoratorExcelConfigData = Vec<QuestDialogDecoratorExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct QuestDialogDecoratorExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "MCGPFPGGCDH")]
    pub mcgpfpggcdh: String,
}

pub fn load() -> Result<QuestDialogDecoratorExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "QuestDialogDecoratorExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
