/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type QuestCatalogExcelConfigData = Vec<QuestCatalogExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuestCatalogExcelConfigDatum {
    pub id: i64,
    #[serde(rename = "LBMMEAEFEPN")]
    pub lbmmeaefepn: Vec<i64>,
    pub quest_id: Vec<i64>,
    #[serde(rename = "AOIODFGHFJG")]
    pub aoiodfghfjg: Vec<Option<serde_json::Value>>,
    #[serde(rename = "EPFIDNGJLEB")]
    pub epfidngjleb: Vec<i64>,
    pub title_text_map_hash: i64,
    pub pic: String,
}
