/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type QuestCatalogGuideExcelConfigData = Vec<QuestCatalogGuideExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuestCatalogGuideExcelConfigDatum {
    pub id: i64,
    pub quest_id: i64,
    pub desc_text_map_hash: i64,
    #[serde(rename = "AECBFDJNBHA")]
    pub aecbfdjnbha: Option<i64>,
}
