// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type QuestPlaceConfigData = Vec<QuestPlaceConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct QuestPlaceConfigDatum {
    #[serde(rename = "placeId")]
    pub place_id: i64,
}

pub fn load() -> Result<QuestPlaceConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "QuestPlaceConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
