/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type QuickTimeCombatBuffExcelConfigData = Vec<QuickTimeCombatBuffExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct QuickTimeCombatBuffExcelConfigDatum {
    pub buff_id: i64,
    pub ability_group_name: String,
    pub cost: i64,
    #[serde(rename = "KAKFHILMHOC")]
    pub kakfhilmhoc: i64,
    pub icon_path: String,
    #[serde(rename = "PCBENBCFINH")]
    pub pcbenbcfinh: Vec<i64>,
    pub description_text_map_hash: i64,
}
