// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type RadarHintExcelConfigData = Vec<RadarHintExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct RadarHintExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "CDDDFGLMLIM")]
    pub cdddfglmlim: String,

    #[serde(rename = "name")]
    pub name: String,

    #[serde(rename = "radius")]
    pub radius: f64,

    #[serde(rename = "effectName")]
    pub effect_name: EffectName,

    #[serde(rename = "iconName")]
    pub icon_name: String,

    #[serde(rename = "audioName")]
    pub audio_name: AudioName,

    #[serde(rename = "PCIIFMHFMKH")]
    pub pciifmhfmkh: Vec<Option<serde_json::Value>>,

    #[serde(rename = "offsetRadius")]
    pub offset_radius: Option<f64>,

    #[serde(rename = "areaRadius")]
    pub area_radius: Option<f64>,

    #[serde(rename = "PJODOAHGPKB")]
    pub pjodoahgpkb: Option<bool>,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum AudioName {
    #[serde(rename = "")]
    Empty,

    #[serde(rename = "Play_ui_feedback_windCrystal_appear")]
    PlayUiFeedbackWindCrystalAppear,
}

#[derive(Debug, Serialize, Deserialize)]
pub enum EffectName {
    #[serde(rename = "Eff_UI_Mark_WindCrystal")]
    EffUiMarkWindCrystal,

    #[serde(rename = "")]
    Empty,
}

pub fn load() -> Result<RadarHintExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "RadarHintExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
