/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type RefreshIndexExcelConfigData = Vec<RefreshIndexExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct RefreshIndexExcelConfigDatum {
    pub priority: i64,
    #[serde(rename = "type")]
    pub refresh_index_excel_config_datum_type: Option<Type>,
    pub name: String,
    pub refresh_id: i64,
    pub rarity: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Type {
    #[serde(rename = "REFRESHINDEX_GADGET")]
    RefreshindexGadget,
}
