/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ReliquaryLevelExcelConfigData = Vec<ReliquaryLevelExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ReliquaryLevelExcelConfigDatum {
    pub level: i64,
    pub add_props: Vec<AddProp>,
    pub rank: Option<i64>,
    pub exp: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct AddProp {
    pub prop_type: PropType,
    pub value: f64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum PropType {
    #[serde(rename = "FIGHT_PROP_ATTACK")]
    FightPropAttack,
    #[serde(rename = "FIGHT_PROP_ATTACK_PERCENT")]
    FightPropAttackPercent,
    #[serde(rename = "FIGHT_PROP_CHARGE_EFFICIENCY")]
    FightPropChargeEfficiency,
    #[serde(rename = "FIGHT_PROP_CRITICAL")]
    FightPropCritical,
    #[serde(rename = "FIGHT_PROP_CRITICAL_HURT")]
    FightPropCriticalHurt,
    #[serde(rename = "FIGHT_PROP_DEFENSE")]
    FightPropDefense,
    #[serde(rename = "FIGHT_PROP_DEFENSE_PERCENT")]
    FightPropDefensePercent,
    #[serde(rename = "FIGHT_PROP_ELEC_ADD_HURT")]
    FightPropElecAddHurt,
    #[serde(rename = "FIGHT_PROP_ELEMENT_MASTERY")]
    FightPropElementMastery,
    #[serde(rename = "FIGHT_PROP_FIRE_ADD_HURT")]
    FightPropFireAddHurt,
    #[serde(rename = "FIGHT_PROP_FIRE_SUB_HURT")]
    FightPropFireSubHurt,
    #[serde(rename = "FIGHT_PROP_GRASS_ADD_HURT")]
    FightPropGrassAddHurt,
    #[serde(rename = "FIGHT_PROP_HEAL_ADD")]
    FightPropHealAdd,
    #[serde(rename = "FIGHT_PROP_HP")]
    FightPropHp,
    #[serde(rename = "FIGHT_PROP_HP_PERCENT")]
    FightPropHpPercent,
    #[serde(rename = "FIGHT_PROP_ICE_ADD_HURT")]
    FightPropIceAddHurt,
    #[serde(rename = "FIGHT_PROP_PHYSICAL_ADD_HURT")]
    FightPropPhysicalAddHurt,
    #[serde(rename = "FIGHT_PROP_ROCK_ADD_HURT")]
    FightPropRockAddHurt,
    #[serde(rename = "FIGHT_PROP_WATER_ADD_HURT")]
    FightPropWaterAddHurt,
    #[serde(rename = "FIGHT_PROP_WIND_ADD_HURT")]
    FightPropWindAddHurt,
}
