/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type RogueDiaryPreviewExcelConfigData = Vec<RogueDiaryPreviewExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct RogueDiaryPreviewExcelConfigDatum {
    #[serde(rename = "activityId")]
    pub activity_id: i64,
    pub aglaojkglji: i64,
    pub knbfalhgjln: i64,
    pub bbfhbcnedhp: Vec<i64>,
    pub lpadopbkejf: Vec<i64>,
    pub efohheobhfi: Vec<i64>,
    pub niehangcjhj: i64,
    pub fklngdgjleo: i64,
    #[serde(rename = "worldSceneId")]
    pub world_scene_id: i64,
}
