// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type RoguelikeShikigamiGroupExcelConfigData = Vec<RoguelikeShikigamiGroupExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct RoguelikeShikigamiGroupExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "KIKGLNIKGFG")]
    pub kikglnikgfg: Kikglnikgfg,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct Kikglnikgfg {
    #[serde(rename = "effectType")]
    pub effect_type: String,

    #[serde(rename = "BHCHCKJGHGG")]
    pub bhchckjghgg: String,

    #[serde(rename = "KMMOMGBGEGO")]
    pub kmmomgbgego: String,
}

pub fn load() -> Result<RoguelikeShikigamiGroupExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "RoguelikeShikigamiGroupExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
