// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type RogueDiaryStageExcelConfigData = Vec<RogueDiaryStageExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct RogueDiaryStageExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "condId")]
    pub cond_id: i64,

    #[serde(rename = "PBBBIOPKCAI")]
    pub pbbbiopkcai: Vec<i64>,

    #[serde(rename = "MCIMHJLHIFJ")]
    pub mcimhjlhifj: Vec<i64>,

    #[serde(rename = "FFEJNELDLBI")]
    pub ffejneldlbi: Vec<i64>,

    #[serde(rename = "PNPBLPOKOJJ")]
    pub pnpblpokojj: i64,

    #[serde(rename = "HENKLCIGBGP")]
    pub henklcigbgp: i64,

    #[serde(rename = "KEABOJCBIHN")]
    pub keabojcbihn: String,

    #[serde(rename = "IABBNCDFIGJ")]
    pub iabbncdfigj: Option<i64>,

    #[serde(rename = "HCNBJHGCIHC")]
    pub hcnbjhgcihc: Vec<i64>,

    #[serde(rename = "CAPBAJIHODB")]
    pub capbajihodb: Vec<i64>,

    #[serde(rename = "watcherIdList")]
    pub watcher_id_list: Vec<i64>,

    #[serde(rename = "pushTipsId")]
    pub push_tips_id: i64,

    #[serde(rename = "AOAMGBJANDP")]
    pub aoamgbjandp: i64,

    #[serde(rename = "FOMCEGDAJHE")]
    pub fomcegdajhe: i64,

    #[serde(rename = "PDJFFAOBBOE")]
    pub pdjffaobboe: Option<i64>,
}

pub fn load() -> Result<RogueDiaryStageExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "RogueDiaryStageExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
