// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type SeaLampSectionMiniQuestExcelConfigData = Vec<SeaLampSectionMiniQuestExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct SeaLampSectionMiniQuestExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "sectionId")]
    pub section_id: i64,

    #[serde(rename = "openDay")]
    pub open_day: i64,

    #[serde(rename = "miniQuestId")]
    pub mini_quest_id: i64,

    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,

    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,

    #[serde(rename = "isSpecial")]
    pub is_special: Option<bool>,
}

pub fn load() -> Result<SeaLampSectionMiniQuestExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "SeaLampSectionMiniQuestExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
