/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ServerMessageExcelConfigData = Vec<ServerMessageExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct ServerMessageExcelConfigDatum {
    pub id: i64,
    pub content_text_map_hash: i64,
    pub show_type: String,
}
