// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type ShopmallGoodsSaleConfigData = Vec<ShopmallGoodsSaleConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct ShopmallGoodsSaleConfigDatum {
    #[serde(rename = "Id")]
    pub id: i64,

    #[serde(rename = "goodsId")]
    pub goods_id: i64,

    #[serde(rename = "OIPBBKLNJEN")]
    pub oipbbklnjen: i64,

    #[serde(rename = "discountRate")]
    pub discount_rate: f64,

    #[serde(rename = "COFCJHFDPML")]
    pub cofcjhfdpml: String,

    #[serde(rename = "DNFKPFLHKMG")]
    pub dnfkpflhkmg: String,
}

pub fn load() -> Result<ShopmallGoodsSaleConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "ShopmallGoodsSaleConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
