/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type SorushTrialPhotoMatchGalleryExcelConfigData = Vec<SorushTrialPhotoMatchGalleryExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct SorushTrialPhotoMatchGalleryExcelConfigDatum {
    #[serde(rename = "GDIJAGPJCPO")]
    pub gdijagpjcpo: Vec<f64>,
    #[serde(rename = "AIICPFOPAFG")]
    pub aiicpfopafg: Vec<f64>,
    #[serde(rename = "JMCIKJIFLNA")]
    pub jmcikjiflna: i64,
    pub id: i64,
    pub gallery_id: i64,
    #[serde(rename = "LBIJMAAKOGF")]
    pub lbijmaakogf: i64,
    #[serde(rename = "OAJNOEJKAFH")]
    pub oajnoejkafh: i64,
    pub level_title_text_map_hash: i64,
    pub level_desc_text_map_hash: i64,
    #[serde(rename = "groupLinkID")]
    pub group_link_id: i64,
    #[serde(rename = "groupID")]
    pub group_id: i64,
    pub watcher_list: Vec<i64>,
}
