/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type TargetShootingLevelExcelConfigData = Vec<TargetShootingLevelExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct TargetShootingLevelExcelConfigDatum {
    #[serde(rename = "levelId")]
    pub level_id: i64,
    #[serde(rename = "stage")]
    pub stage: i64,
    pub ndifjdaabpm: Vec<i64>,
    #[serde(rename = "galleryId")]
    pub gallery_id: i64,
    #[serde(rename = "groupId")]
    pub group_id: i64,
    pub pbhlikpbfoc: i64,
    pub gdlbmpnbofj: i64,
    pub oknjhkillno: i64,
    pub hnfidpdkdko: i64,
    pub eebmcpgcjlk: Vec<i64>,
    pub jaadplimlhj: Vec<i64>,
    pub eiffjkbibjo: i64,
    pub pmdpodakafe: i64,
    #[serde(rename = "draftId")]
    pub draft_id: i64,
    #[serde(rename = "titleTextMapHash")]
    pub title_text_map_hash: i64,
    #[serde(rename = "descTextMapHash")]
    pub desc_text_map_hash: i64,
    #[serde(rename = "watcherList")]
    pub watcher_list: Vec<i64>,
    pub cjliilicgkp: i64,
    #[serde(rename = "scoreLevelList")]
    pub score_level_list: Vec<i64>,
    pub bfeaknphjai: Option<i64>,
    pub miehombhocb: i64,
    pub egpnlelngoa: i64,
    pub moipoljihhj: i64,
    pub nfcnfajigjf: Option<i64>,
}
