// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type TeamChainBuffExcelConfigData = Vec<TeamChainBuffExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct TeamChainBuffExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "LADKLKNNEKD")]
    pub ladklknnekd: String,

    #[serde(rename = "icon")]
    pub icon: String,

    #[serde(rename = "buffNameTextMapHash")]
    pub buff_name_text_map_hash: i64,

    #[serde(rename = "EOPGNNKMNGO")]
    pub eopgnnkmngo: i64,

    #[serde(rename = "NBDPLIKACFG")]
    pub nbdplikacfg: Vec<String>,
}

pub fn load() -> Result<TeamChainBuffExcelConfigData, crate::json::JsonError> {
    let game_resources_path = std::env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "TeamChainBuffExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
