/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type TeamBackgroundWorldExcelConfigData = Vec<TeamBackgroundWorldExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TeamBackgroundWorldExcelConfigDatum {
    pub id: i64,
    pub path: String,
    #[serde(rename = "PIDFHFOGENG")]
    pub pidfhfogeng: Vec<i64>,
    pub param_list: Vec<i64>,
    #[serde(rename = "type")]
    pub team_background_world_excel_config_datum_type: Option<String>,
}
