// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type TowerRewardExcelConfigData = Vec<TowerRewardExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct TowerRewardExcelConfigDatum {
    #[serde(rename = "IEPBHNILIDB")]
    pub iepbhnilidb: i64,

    #[serde(rename = "DGKHCGBPFDM")]
    pub dgkhcgbpfdm: i64,

    #[serde(rename = "BCOFGJBABGD")]
    pub bcofgjbabgd: i64,

    #[serde(rename = "CAEOHANFNAP")]
    pub caeohanfnap: i64,

    #[serde(rename = "DGJDIBJKGMI")]
    pub dgjdibjkgmi: i64,

    #[serde(rename = "MHDLDDFOIJD")]
    pub mhdlddfoijd: Vec<i64>,
}

pub fn load() -> Result<TowerRewardExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "TowerRewardExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
