/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type TrialAvatarExcelConfigData = Vec<TrialAvatarExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct TrialAvatarExcelConfigDatum {
    pub trial_avatar_id: i64,
    pub trial_avatar_param_list: Vec<i64>,
    pub is_dynamic_level: Option<bool>,
    pub specified_costume_id: Option<i64>,
    #[serde(rename = "HKJIEBCMFNF")]
    pub hkjiebcmfnf: Option<bool>,
    pub trial_skill_depot_id: Option<i64>,
}
