/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type UgcGlobalExcelConfigData = Vec<UgcGlobalExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct UgcGlobalExcelConfigDatum {
    pub id: i64,
    pub nlgjklkhjbd: String,
    pub pgkcmgijjkn: i64,
    #[serde(rename = "dungeonId")]
    pub dungeon_id: i64,
    pub nhnbnpncddo: Vec<i64>,
    pub ekonfnldgep: i64,
    pub hhojhknnpim: i64,
    pub gblelidpcia: i64,
    pub nbkkmianedo: i64,
    pub ahdkkogeafe: Vec<i64>,
    pub oihmhoflada: Vec<i64>,
    pub cpkkjagfaen: Vec<i64>,
    pub ncpnmjohian: Vec<i64>,
    pub nkpjbofpaom: i64,
    #[serde(rename = "controlGroupId")]
    pub control_group_id: i64,
    pub iapkkkpldja: i64,
    pub gfmfcjoojfm: i64,
    pub nofhchbjden: i64,
    pub mdmgplnfbof: i64,
    pub kgddaelolmn: i64,
    pub jcjpnjcgkpk: i64,
    pub mcjelobclnp: i64,
    pub iiegekbpgio: i64,
    pub cceoncoahhp: i64,
    pub mfpppiijddk: i64,
    pub dkcdmebdakm: i64,
    pub gbiedglkbld: i64,
    pub mjpbiipcjck: i64,
    pub lhoohapbjoi: i64,
    pub idnfmannoej: String,
    pub ochkhbeimlg: i64,
    pub jjhldcpahgi: Vec<i64>,
    pub mhphbfnnhoa: i64,
    pub gjncihkkknp: i64,
    pub eogapbocaik: i64,
    pub mamjdkelaco: String,
    pub bghipbdbhla: Vec<i64>,
    pub ieblgbbgejd: i64,
    pub mfcolffdoko: i64,
    pub ademngjgcpf: i64,
    pub amaklniejgp: i64,
    pub nhahoamkegk: i64,
    pub oijbblbedbo: i64,
    pub bmdcmdjjdaj: i64,
    pub flbcaaaofpd: Vec<i64>,
    pub hgpjbkileic: Vec<i64>,
    pub linapmoipkm: i64,
    pub fefmgnfbbcj: i64,
    pub dfniddcbfcn: i64,
    pub jkhhinaofcj: i64,
}
