/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type UgcMaterialExcelConfigData = Vec<UgcMaterialExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct UgcMaterialExcelConfigDatum {
    #[serde(rename = "materialId")]
    pub material_id: i64,
    pub kmjmgjkkgnf: i64,
    pub ffeppgfcgbd: i64,
    pub jlmpoifdngj: i64,
    pub hmcbihmbgkn: f64,
    pub hepdkgcepmj: i64,
    #[serde(rename = "type")]
    pub ugc_material_excel_config_datum_type: Option<Type>,
    #[serde(rename = "tag")]
    pub tag: Option<i64>,
    #[serde(rename = "indexId")]
    pub index_id: Option<i64>,
    #[serde(rename = "stackLimit")]
    pub stack_limit: Option<i64>,
    pub acjbbplendf: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub enum Type {
    #[serde(rename = "UGC_MATERIAL_TYPE_AVATAR")]
    UgcMaterialTypeAvatar,
    #[serde(rename = "UGC_MATERIAL_TYPE_BUFF")]
    UgcMaterialTypeBuff,
    #[serde(rename = "UGC_MATERIAL_TYPE_COIN")]
    UgcMaterialTypeCoin,
    #[serde(rename = "UGC_MATERIAL_TYPE_EXP")]
    UgcMaterialTypeExp,
}
