/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type UgcMonsterExcelConfigData = Vec<UgcMonsterExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct UgcMonsterExcelConfigDatum {
    pub miibmidhoid: Miibmidhoid,
    #[serde(rename = "monsterId")]
    pub monster_id: i64,
    pub cjibbampkml: f64,
    pub gkabbkpfnnk: String,
    pub mjnjdoaogdp: i64,
    pub dbnifekegli: i64,
    pub oojhgbneijd: i64,
    pub keibjnfbcij: i64,
    pub bdojdfhcnck: Vec<Bdojdfhcnck>,
    pub ogcefklakfl: i64,
    #[serde(rename = "id")]
    pub id: i64,
    pub fgdknngbjha: Vec<Option<serde_json::Value>>,
    #[serde(rename = "nameTextMapHash")]
    pub name_text_map_hash: i64,
    #[serde(rename = "cost")]
    pub cost: i64,
    pub eaakebfejel: Eaakebfejel,
    #[serde(rename = "deployGadgetID")]
    pub deploy_gadget_id: i64,
    pub ijoihabekce: Option<bool>,
    pub ghmfbmnahop: Option<f64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct Bdojdfhcnck {
    pub eejogmflihb: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Eaakebfejel {
    #[serde(rename = "MonsterModelL1W1H2")]
    MonsterModelL1W1H2,
    #[serde(rename = "MonsterModelL2W2H2")]
    MonsterModelL2W2H2,
    #[serde(rename = "MonsterModelL2W2H3")]
    MonsterModelL2W2H3,
    #[serde(rename = "MonsterModelL2W4H3")]
    MonsterModelL2W4H3,
    #[serde(rename = "MonsterModelL3W3H3")]
    MonsterModelL3W3H3,
    #[serde(rename = "MonsterModelL50W50H15")]
    MonsterModelL50W50H15,
    #[serde(rename = "MonsterModelL5W10H10")]
    MonsterModelL5W10H10,
    #[serde(rename = "MonsterModelL5W5H5")]
    MonsterModelL5W5H5,
    #[serde(rename = "MonsterModelL7W7H8")]
    MonsterModelL7W7H8,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum Miibmidhoid {
    #[serde(rename = "MonsterSkill10W10H10")]
    MonsterSkill10W10H10,
    #[serde(rename = "MonsterSkillL1W1H2")]
    MonsterSkillL1W1H2,
    #[serde(rename = "MonsterSkillL2W2H2")]
    MonsterSkillL2W2H2,
    #[serde(rename = "MonsterSkillL2W2H3")]
    MonsterSkillL2W2H3,
    #[serde(rename = "MonsterSkillL2W4H3")]
    MonsterSkillL2W4H3,
    #[serde(rename = "MonsterSkillL3W3H3")]
    MonsterSkillL3W3H3,
    #[serde(rename = "MonsterSkillL50W50H15")]
    MonsterSkillL50W50H15,
    #[serde(rename = "MonsterSkillL5W10H10")]
    MonsterSkillL5W10H10,
    #[serde(rename = "MonsterSkillL5W5H5")]
    MonsterSkillL5W5H5,
}
