/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type UgcOfficialLevelExcelConfigData = Vec<UgcOfficialLevelExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UgcOfficialLevelExcelConfigDatum {
    pub id: i64,
    #[serde(rename = "CNDPKBFCOJC")]
    pub cndpkbfcojc: i64,
    pub unlock_day: i64,
    pub level_name_text_map_hash: i64,
    pub level_desc_text_map_hash: i64,
    pub preview_path: String,
    #[serde(rename = "PJLJEEDDOII")]
    pub pjljeeddoii: Vec<i64>,
    #[serde(rename = "ODMPGPMJCBF")]
    pub odmpgpmjcbf: i64,
    #[serde(rename = "MOHMMMJJJJI")]
    pub mohmmmjjjji: f64,
}
