/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type UgcTowerLevelExcelConfigData = Vec<UgcTowerLevelExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct UgcTowerLevelExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "gadgetId")]
    pub gadget_id: i64,
    pub ehmamgclofp: i64,
    #[serde(rename = "descParam")]
    pub desc_param: Vec<String>,
    #[serde(rename = "level")]
    pub level: Option<i64>,
    pub gifbcdndgbb: Option<i64>,
    pub mfmgmkdjndl: Option<i64>,
    pub pmfplbddimf: Option<i64>,
}
