/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type UidOpNotifyExcelConfigData = Vec<UidOpNotifyExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct UidOpNotifyExcelConfigDatum {
    pub id: i64,
    pub content_text_map_hash: i64,
}
