/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type VehicleSkillDepotExcelConfigData = Vec<VehicleSkillDepotExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct VehicleSkillDepotExcelConfigDatum {
    pub id: i64,
    pub biefpoggcnn: Vec<i64>,
}
