/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type VehicleSkillExcelConfigData = Vec<VehicleSkillExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct VehicleSkillExcelConfigDatum {
    pub id: i64,
    pub dlehbdcbheh: i64,
    pub kpkhpjmelnk: i64,
    #[serde(rename = "abilityName")]
    pub ability_name: String,
    #[serde(rename = "skillIcon")]
    pub skill_icon: String,
    pub fbmmklhjcob: i64,
    pub enefocefmgj: i64,
    #[serde(rename = "lockShape")]
    pub lock_shape: LockShape,
    #[serde(rename = "lockWeightParams")]
    pub lock_weight_params: Vec<f64>,
    #[serde(rename = "globalValueKey")]
    pub global_value_key: String,
    pub gmecaomjjhf: Option<i64>,
    pub eehcdojfdlc: Option<i64>,
    pub dppkgebmoah: Option<String>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum LockShape {
    #[serde(rename = "CircleLockEnemyR50H15BC")]
    CircleLockEnemyR50H15Bc,
    #[serde(rename = "CircleLockEnemyR5H6HC")]
    CircleLockEnemyR5H6Hc,
}
