/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type VintageMarketRoundExcelConfigData = Vec<VintageMarketRoundExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VintageMarketRoundExcelConfigDatum {
    pub id: i64,
    #[serde(rename = "LMGCFOBCFAE")]
    pub lmgcfobcfae: Vec<Lmgcfobcfae>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct Lmgcfobcfae {
    pub imodcoekpmj: Vec<f64>,
    pub mhohkcbjpkb: i64,
    pub alackimgbhb: f64,
    pub hljkfceggpf: Option<i64>,
    pub gjeegnnhale: f64,
}
