/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type VintageMarketNpcEventExcelConfigData = Vec<VintageMarketNpcEventExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct VintageMarketNpcEventExcelConfigDatum {
    pub id: i64,
    pub talk_id: i64,
    pub npc_id: i64,
    pub duration: i64,
    #[serde(rename = "KPLOOFONFDD")]
    pub kploofonfdd: Vec<i64>,
    #[serde(rename = "DGLPPIEPKCF")]
    pub dglppiepkcf: Vec<Dglppiepkcf>,
    #[serde(rename = "OHADKFLDKOK")]
    pub ohadkfldkok: i64,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct Dglppiepkcf {
    pub talk_id: Option<i64>,
    pub reward_id: Option<i64>,
}
