/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type VintageMarketAttrUpgradeExcelConfigData = Vec<VintageMarketAttrUpgradeExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct VintageMarketAttrUpgradeExcelConfigDatum {
    #[serde(rename = "BFIADBCKKGE")]
    pub bfiadbckkge: Vec<Bfiadbckkge>,
    pub id: Option<i64>,
}

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct Bfiadbckkge {
    pub elipojoccfa: Vec<i64>,
}
