/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type WidgetExcelConfigData = Vec<WidgetExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WidgetExcelConfigDatum {
    #[serde(rename = "materialID")]
    pub material_id: i64,
    pub customize_desc: Vec<i64>,
    pub json_addr: Option<bool>,
    pub push_tips_id: Option<i64>,
}
