/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type WidgetCameraExcelConfigData = Vec<WidgetCameraExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct WidgetCameraExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    pub mjeafnemfbh: i64,
    pub ogofghbafja: String,
    pub pelpiokdhje: i64,
    pub gaaeilihmom: i64,
    pub odmcfbdobch: i64,
}
