// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type WidgetActiveExcelConfigData = Vec<WidgetActiveExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct WidgetActiveExcelConfigDatum {
    #[serde(rename = "materialID")]
    pub material_id: i64,

    #[serde(rename = "LDDJFKFPKKG")]
    pub lddjfkfpkkg: Vec<i64>,

    #[serde(rename = "GFDGGGMDFKM")]
    pub gfdgggmdfkm: String,

    #[serde(rename = "FEALBOMBNKG")]
    pub fealbombnkg: Vec<i64>,

    #[serde(rename = "JCNLMMHFEKG")]
    pub jcnlmmhfekg: Vec<i64>,

    #[serde(rename = "DLFNEHADIBF")]
    pub dlfnehadibf: Option<bool>,
}

pub fn load() -> Result<WidgetActiveExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "WidgetActiveExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
