/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type WidgetGeneralExcelConfigData = Vec<WidgetGeneralExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WidgetGeneralExcelConfigDatum {
    #[serde(rename = "materialID")]
    pub material_id: i64,
    pub can_use_in_other_world: Option<bool>,
    pub forbidden_scene_id_list: Vec<i64>,
    #[serde(rename = "PINAGECHOKP")]
    pub pinagechokp: Option<bool>,
    pub forbidden_dungeon_type_list: Vec<i64>,
    pub forbidden_dungeon_play_type_list: Vec<i64>,
    #[serde(rename = "DAGABBDADIA")]
    pub dagabbdadia: Vec<i64>,
    #[serde(rename = "NCIBBPCAGJO")]
    pub ncibbpcagjo: Option<bool>,
    pub can_use_in_dungeon: Option<bool>,
    pub can_use_in_homeworld: Option<bool>,
    #[serde(rename = "BMAHNNLIHCN")]
    pub bmahnnlihcn: Option<bool>,
    pub can_use_in_room: Option<bool>,
    pub can_use_in_limit_region: Option<bool>,
    pub can_use_when_fight: Option<bool>,
    pub can_use_in_un_normal_move_state: Option<bool>,
    pub can_use_in_avatar_focus: Option<bool>,
    pub can_use_when_current_avatar_dead: Option<bool>,
    pub vehicle_limit: Option<String>,
    #[serde(rename = "KNBIGELHDGA")]
    pub knbigelhdga: Option<bool>,
    #[serde(rename = "EMAOLEMHKAG")]
    pub emaolemhkag: Option<bool>,
}
