// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

use std::env;

extern crate serde_derive;

pub type WidgetCameraExcelConfigData = Vec<WidgetCameraExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct WidgetCameraExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "NFIHOPNFONO")]
    pub nfihopnfono: f64,

    #[serde(rename = "GIIEEOOFECK")]
    pub giieeoofeck: String,

    #[serde(rename = "GPLDOLGDACP")]
    pub gpldolgdacp: i64,

    #[serde(rename = "HFBDHHADACP")]
    pub hfbdhhadacp: i64,

    #[serde(rename = "LPDNHAPLBLO")]
    pub lpdnhaplblo: i64,
}

pub fn load() -> Result<WidgetCameraExcelConfigData, crate::json::JsonError> {
    let game_resources_path = env::var("GAME_DATA_PATH").unwrap();
    let path: std::path::PathBuf = [
        game_resources_path.as_str(),
        "ExcelBinOutput",
        "WidgetCameraExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
