/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type WindFieldShowChallengeExcelConfigData = Vec<WindFieldShowChallengeExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct WindFieldShowChallengeExcelConfigDatum {
    pub ocnnbpkenci: i64,
    pub hfmllbddmmk: Option<i64>,
    #[serde(rename = "showType")]
    pub show_type: String,
    pub pghojacflgb: Vec<i64>,
    #[serde(rename = "titleTextMapHash")]
    pub title_text_map_hash: i64,
    pub bpcgfppihah: i64,
    pub koilccinjgn: i64,
    #[serde(rename = "timeLimit")]
    pub time_limit: Option<i64>,
}
