/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type WinterCampRaceExcelConfigData = Vec<WinterCampRaceExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "SCREAMING_SNAKE_CASE")]
pub struct WinterCampRaceExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,
    #[serde(rename = "openDay")]
    pub open_day: i64,
    #[serde(rename = "galleryId")]
    pub gallery_id: i64,
    pub dgjnhbgfbak: i64,
    pub ggcfdfanmhh: Vec<i64>,
    pub bfcgomfgpmo: Vec<i64>,
    pub pabmlaffdal: i64,
    pub beahefgkljl: i64,
    pub oheepgnccop: i64,
    pub eajajlpnopa: Vec<i64>,
}
