// This file was automatically generated by quicktype and a custom PowerShell script
// (see Sync-ExcelBinOutput.ps1 for more info).
// DO NOT manually edit this file!

extern crate serde_derive;

pub type WinterCampSnowmanDetailExcelConfigData = Vec<WinterCampSnowmanDetailExcelConfigDatum>;

#[derive(Debug, Serialize, Deserialize)]
pub struct WinterCampSnowmanDetailExcelConfigDatum {
    #[serde(rename = "id")]
    pub id: i64,

    #[serde(rename = "ENGOHEGBMMM")]
    pub engohegbmmm: i64,

    #[serde(rename = "OIBAMLDNBGF")]
    pub oibamldnbgf: i64,

    #[serde(rename = "LEJHEBAMEDL")]
    pub lejhebamedl: i64,

    #[serde(rename = "LDFCGLCBMMK")]
    pub ldfcglcbmmk: i64,

    #[serde(rename = "watcherId")]
    pub watcher_id: i64,
}

pub fn load() -> Result<WinterCampSnowmanDetailExcelConfigData, crate::json::JsonError> {
    let path: std::path::PathBuf = [
        "GenshinData",
        "ExcelBinOutput",
        "WinterCampSnowmanDetailExcelConfigData.json",
    ]
    .iter()
    .collect();
    crate::json::load_json(path)
}
