/// This file was automatically generated by quicktype
/// DO NOT MANUALLY EDIT THIS FILE!

#[allow(unused_imports)]
use serde::{Serialize, Deserialize};

pub type WorldExcelConfigData = Vec<WorldExcelConfigDatum>;

#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(rename_all = "camelCase")]
pub struct WorldExcelConfigDatum {
    pub id: i64,
    #[serde(rename = "type")]
    pub world_excel_config_datum_type: String,
    pub main_scene_id: i64,
    pub sub_scene_id_vec: Vec<i64>,
}
